// internal/mocks/mock_db_interface.go
// Code generated by MockGen. DO NOT EDIT.
// Source: internal/db/db_interface.go
// Package mocks provides mock implementations of interfaces for testing purposes.
// This file contains a mock implementation of the DBInterface defined in the `internal/db` package.
// It is generated using the `gomock` tool and is used to simulate database interactions in unit tests.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockDBInterface is a mock implementation of the DBInterface.
// It is used to simulate database operations in unit tests.
type MockDBInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDBInterfaceMockRecorder
}

// MockDBInterfaceMockRecorder is the mock recorder for MockDBInterface.
// It records method calls and allows setting expected return values.
type MockDBInterfaceMockRecorder struct {
	mock *MockDBInterface
}

// NewMockDBInterface creates a new mock instance of DBInterface.
// It initializes the mock with the provided gomock.Controller.
func NewMockDBInterface(ctrl *gomock.Controller) *MockDBInterface {
	mock := &MockDBInterface{ctrl: ctrl}
	mock.recorder = &MockDBInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use of the mock.
// It is used to set expectations for method calls and define their behavior.
func (m *MockDBInterface) EXPECT() *MockDBInterfaceMockRecorder {
	return m.recorder
}

// WithContext mocks the WithContext method of DBInterface.
// It simulates attaching a context to the database instance.
func (m *MockDBInterface) WithContext(ctx context.Context) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithContext", ctx)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// WithContext indicates an expected call of WithContext.
func (mr *MockDBInterfaceMockRecorder) WithContext(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithContext", reflect.TypeOf((*MockDBInterface)(nil).WithContext), ctx)
}

// Begin mocks the Begin method of DBInterface.
// It simulates starting a new database transaction.
func (m *MockDBInterface) Begin(ctx context.Context) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", ctx)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Begin indicates an expected call of Begin.
func (mr *MockDBInterfaceMockRecorder) Begin(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockDBInterface)(nil).Begin), ctx)
}

// Commit mocks the Commit method of DBInterface.
// It simulates committing the current database transaction.
func (m *MockDBInterface) Commit(ctx context.Context) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit", ctx)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockDBInterfaceMockRecorder) Commit(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockDBInterface)(nil).Commit), ctx)
}

// Create mocks the Create method of DBInterface.
// It simulates inserting a new record into the database.
func (m *MockDBInterface) Create(ctx context.Context, value interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, value)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDBInterfaceMockRecorder) Create(ctx, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDBInterface)(nil).Create), ctx, value)
}

// Delete mocks the Delete method of DBInterface.
// It simulates deleting a record from the database.
func (m *MockDBInterface) Delete(ctx context.Context, value interface{}, conds ...interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, value}
	for _, a := range conds {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDBInterfaceMockRecorder) Delete(ctx, value interface{}, conds ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, value}, conds...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDBInterface)(nil).Delete), varargs...)
}

// Find mocks the Find method of DBInterface.
// It simulates retrieving records from the database.
func (m *MockDBInterface) Find(ctx context.Context, dest interface{}, conds ...interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, dest}
	for _, a := range conds {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Find", varargs...)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Find indicates an expected call of Find.
func (mr *MockDBInterfaceMockRecorder) Find(ctx, dest interface{}, conds ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, dest}, conds...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockDBInterface)(nil).Find), varargs...)
}

// First mocks the First method of DBInterface.
// It simulates retrieving the first record matching the given conditions.
func (m *MockDBInterface) First(ctx context.Context, dest interface{}, conds ...interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, dest}
	for _, a := range conds {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "First", varargs...)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// First indicates an expected call of First.
func (mr *MockDBInterfaceMockRecorder) First(ctx, dest interface{}, conds ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, dest}, conds...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "First", reflect.TypeOf((*MockDBInterface)(nil).First), varargs...)
}

// GetError mocks the GetError method of DBInterface.
// It simulates retrieving the last error encountered during database operations.
func (m *MockDBInterface) GetError() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetError")
	ret0, _ := ret[0].(error)
	return ret0
}

// GetError indicates an expected call of GetError.
func (mr *MockDBInterfaceMockRecorder) GetError() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetError", reflect.TypeOf((*MockDBInterface)(nil).GetError))
}

// Limit mocks the Limit method of DBInterface.
// It simulates limiting the number of records returned in the result set.
func (m *MockDBInterface) Limit(limit int) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Limit", limit)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Limit indicates an expected call of Limit.
func (mr *MockDBInterfaceMockRecorder) Limit(limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Limit", reflect.TypeOf((*MockDBInterface)(nil).Limit), limit)
}

// Offset mocks the Offset method of DBInterface.
// It simulates skipping a specified number of records in the result set.
func (m *MockDBInterface) Offset(offset int) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Offset", offset)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Offset indicates an expected call of Offset.
func (mr *MockDBInterfaceMockRecorder) Offset(offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Offset", reflect.TypeOf((*MockDBInterface)(nil).Offset), offset)
}

// Preload mocks the Preload method of DBInterface.
// It simulates eagerly loading related records.
func (m *MockDBInterface) Preload(column string, ctx context.Context, conditions ...interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	varargs := []interface{}{column, ctx}
	for _, a := range conditions {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Preload", varargs...)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Preload indicates an expected call of Preload.
func (mr *MockDBInterfaceMockRecorder) Preload(column, ctx interface{}, conditions ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{column, ctx}, conditions...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Preload", reflect.TypeOf((*MockDBInterface)(nil).Preload), varargs...)
}

// Rollback mocks the Rollback method of DBInterface.
// It simulates rolling back the current database transaction.
func (m *MockDBInterface) Rollback(ctx context.Context) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback", ctx)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockDBInterfaceMockRecorder) Rollback(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockDBInterface)(nil).Rollback), ctx)
}

// Save mocks the Save method of DBInterface.
// It simulates updating or inserting a record in the database.
func (m *MockDBInterface) Save(ctx context.Context, value interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, value)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockDBInterfaceMockRecorder) Save(ctx, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockDBInterface)(nil).Save), ctx, value)
}

// Unscoped mocks the Unscoped method of DBInterface.
// It simulates including soft-deleted records in the query results.
func (m *MockDBInterface) Unscoped(ctx context.Context) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unscoped", ctx)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Unscoped indicates an expected call of Unscoped.
func (mr *MockDBInterfaceMockRecorder) Unscoped(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unscoped", reflect.TypeOf((*MockDBInterface)(nil).Unscoped), ctx)
}

// Where mocks the Where method of DBInterface.
// It simulates filtering records based on the given query and arguments.
func (m *MockDBInterface) Where(ctx context.Context, query interface{}, args ...interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Where", varargs...)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Where indicates an expected call of Where.
func (mr *MockDBInterfaceMockRecorder) Where(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Where", reflect.TypeOf((*MockDBInterface)(nil).Where), varargs...)
}
