package graphql

import (
	"myanimeapi/api/services"
)

// Resolver holds application-layer dependencies injected by the composition root.
// Each resolver file (generated by gqlgen) embeds this struct.
type Resolver struct {
	AnimeService     services.AnimeServiceInterface
	AuthService      services.AuthServiceInterface
	GenreService     services.GenreServiceInterface
	UserService      services.UserServiceInterface
	CharacterService services.CharacterServiceInterface
}
