package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"myanimeapi/api/adapters/graphql/generated"
	"myanimeapi/api/adapters/graphql/model"
	"myanimeapi/api/models"
	"strconv"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, username string, email string, password string) (*model.User, error) {
	user := &models.User{
		Username: username,
		Email:    email,
		Password: password,
		IsActive: true,
	}
	if err := r.AuthService.RegisterUser(ctx, user); err != nil {
		return nil, err
	}
	return &model.User{
		ID:       strconv.FormatUint(uint64(user.ID), 10),
		Username: user.Username,
		Email:    user.Email,
		IsAdmin:  user.IsAdmin,
		IsActive: user.IsActive,
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, username string, password string) (*model.AuthPayload, error) {
	creds := &models.UserCredentials{
		Username: username,
		Password: password,
	}
	token, err := r.AuthService.AuthenticateUser(ctx, creds)
	if err != nil {
		return nil, err
	}
	return &model.AuthPayload{Token: token}, nil
}

// CreateAnime is the resolver for the createAnime field.
func (r *mutationResolver) CreateAnime(ctx context.Context, title string, description *string, episodes *int, status *string) (*model.Anime, error) {
	anime := &models.Anime{Title: title}
	if description != nil {
		anime.Description = *description
	}
	if episodes != nil {
		anime.Episodes = *episodes
	}
	if status != nil {
		anime.Status = *status
	}
	if err := r.AnimeService.CreateAnime(ctx, anime); err != nil {
		return nil, err
	}
	created, err := r.AnimeService.GetAnimeByID(ctx, anime.ID)
	if err != nil {
		return nil, err
	}
	return toGQLAnime(created), nil
}

// DeleteAnime is the resolver for the deleteAnime field.
func (r *mutationResolver) DeleteAnime(ctx context.Context, id string) (bool, error) {
	uid, err := parseID(id)
	if err != nil {
		return false, fmt.Errorf("invalid anime ID: %s", id)
	}
	if err := r.AnimeService.DeleteAnime(ctx, uid); err != nil {
		return false, err
	}
	return true, nil
}

// CreateCharacter is the resolver for the createCharacter field.
func (r *mutationResolver) CreateCharacter(ctx context.Context, name string, description *string, voiceActor *string, imageURL *string) (*model.Character, error) {
	character := &models.Character{Name: name}
	if description != nil {
		character.Description = *description
	}
	if voiceActor != nil {
		character.VoiceActor = *voiceActor
	}
	character.ImageURL = imageURL
	if err := r.CharacterService.CreateCharacter(ctx, character); err != nil {
		return nil, err
	}
	return toGQLCharacter(character), nil
}

// UpdateCharacter is the resolver for the updateCharacter field.
func (r *mutationResolver) UpdateCharacter(ctx context.Context, id string, name *string, description *string, voiceActor *string, imageURL *string) (*model.Character, error) {
	uid, err := parseID(id)
	if err != nil {
		return nil, fmt.Errorf("invalid character ID: %s", id)
	}
	character, err := r.CharacterService.GetCharacterByID(ctx, uid)
	if err != nil {
		return nil, err
	}
	if name != nil {
		character.Name = *name
	}
	if description != nil {
		character.Description = *description
	}
	if voiceActor != nil {
		character.VoiceActor = *voiceActor
	}
	if imageURL != nil {
		character.ImageURL = imageURL
	}
	if err := r.CharacterService.UpdateCharacter(ctx, character); err != nil {
		return nil, err
	}
	return toGQLCharacter(character), nil
}

// DeleteCharacter is the resolver for the deleteCharacter field.
func (r *mutationResolver) DeleteCharacter(ctx context.Context, id string) (bool, error) {
	uid, err := parseID(id)
	if err != nil {
		return false, fmt.Errorf("invalid character ID: %s", id)
	}
	if err := r.CharacterService.DeleteCharacter(ctx, uid); err != nil {
		return false, err
	}
	return true, nil
}

// Anime is the resolver for the anime field.
func (r *queryResolver) Anime(ctx context.Context, id string) (*model.Anime, error) {
	uid, err := parseID(id)
	if err != nil {
		return nil, fmt.Errorf("invalid anime ID: %s", id)
	}
	anime, err := r.AnimeService.GetAnimeByID(ctx, uid)
	if err != nil {
		return nil, err
	}
	return toGQLAnime(anime), nil
}

// Animes is the resolver for the animes field.
func (r *queryResolver) Animes(ctx context.Context, page *int, limit *int, filter *model.AnimeFilterInput) (*model.AnimeList, error) {
	p, l := paginationArgs(page, limit)
	f := models.AnimeFilter{}
	if filter != nil {
		if filter.Status != nil {
			f.Status = *filter.Status
		}
		if filter.Genre != nil {
			f.Genre = *filter.Genre
		}
		if len(filter.Genres) > 0 {
			f.Genres = filter.Genres
		}
		if filter.Tag != nil {
			f.Tag = *filter.Tag
		}
		if len(filter.Tags) > 0 {
			f.Tags = filter.Tags
		}
		if filter.RatingMin != nil {
			f.RatingMin = *filter.RatingMin
		}
		if filter.RatingMax != nil {
			f.RatingMax = *filter.RatingMax
		}
		if filter.EpisodesMin != nil {
			f.EpisodesMin = *filter.EpisodesMin
		}
		if filter.EpisodesMax != nil {
			f.EpisodesMax = *filter.EpisodesMax
		}
		if filter.YearFrom != nil {
			f.YearFrom = *filter.YearFrom
		}
		if filter.YearTo != nil {
			f.YearTo = *filter.YearTo
		}
		if filter.SortBy != nil {
			f.SortBy = *filter.SortBy
		}
		if filter.SortOrder != nil {
			f.SortOrder = *filter.SortOrder
		}
	}
	if err := f.Validate(); err != nil {
		return nil, err
	}
	animes, total, err := r.AnimeService.GetAllAnimes(ctx, p, l, f)
	if err != nil {
		return nil, err
	}
	list := &model.AnimeList{Total: int(total)}
	for _, a := range animes {
		list.Data = append(list.Data, toGQLAnime(a))
	}
	if list.Data == nil {
		list.Data = []*model.Anime{}
	}
	return list, nil
}

// AnimesByTitle is the resolver for the animesByTitle field.
func (r *queryResolver) AnimesByTitle(ctx context.Context, title string, page *int, limit *int, sortBy *string, sortOrder *string) (*model.AnimeList, error) {
	p, l := paginationArgs(page, limit)
	f := models.AnimeFilter{Title: title}
	if sortBy != nil {
		f.SortBy = *sortBy
	}
	if sortOrder != nil {
		f.SortOrder = *sortOrder
	}
	if err := f.Validate(); err != nil {
		return nil, err
	}
	animes, total, err := r.AnimeService.GetAllAnimes(ctx, p, l, f)
	if err != nil {
		return nil, err
	}
	list := &model.AnimeList{Total: int(total)}
	for _, a := range animes {
		list.Data = append(list.Data, toGQLAnime(a))
	}
	if list.Data == nil {
		list.Data = []*model.Anime{}
	}
	return list, nil
}

// Genre is the resolver for the genre field.
func (r *queryResolver) Genre(ctx context.Context, id string) (*model.Genre, error) {
	uid, err := parseID(id)
	if err != nil {
		return nil, fmt.Errorf("invalid genre ID: %s", id)
	}
	genre, err := r.GenreService.GetGenreByID(ctx, uid)
	if err != nil {
		return nil, err
	}
	return toGQLGenre(genre), nil
}

// Genres is the resolver for the genres field.
func (r *queryResolver) Genres(ctx context.Context, page *int, limit *int) ([]*model.Genre, error) {
	p, l := paginationArgs(page, limit)
	genres, _, err := r.GenreService.GetAllGenres(ctx, p, l)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Genre, len(genres))
	for i := range genres {
		result[i] = toGQLGenre(&genres[i])
	}
	return result, nil
}

// Character is the resolver for the character field.
func (r *queryResolver) Character(ctx context.Context, id string) (*model.Character, error) {
	uid, err := parseID(id)
	if err != nil {
		return nil, fmt.Errorf("invalid character ID: %s", id)
	}
	character, err := r.CharacterService.GetCharacterByID(ctx, uid)
	if err != nil {
		return nil, err
	}
	return toGQLCharacter(character), nil
}

// Characters is the resolver for the characters field.
func (r *queryResolver) Characters(ctx context.Context, page *int, limit *int) (*model.CharacterList, error) {
	p, l := paginationArgs(page, limit)
	characters, total, err := r.CharacterService.GetAllCharacters(ctx, p, l)
	if err != nil {
		return nil, err
	}
	list := &model.CharacterList{Total: int(total)}
	for _, c := range characters {
		list.Data = append(list.Data, toGQLCharacter(c))
	}
	if list.Data == nil {
		list.Data = []*model.Character{}
	}
	return list, nil
}

// CharactersByName is the resolver for the charactersByName field.
func (r *queryResolver) CharactersByName(ctx context.Context, name string, page *int, limit *int) (*model.CharacterList, error) {
	p, l := paginationArgs(page, limit)
	characters, total, err := r.CharacterService.GetCharactersByName(ctx, name, p, l)
	if err != nil {
		return nil, err
	}
	list := &model.CharacterList{Total: int(total)}
	for _, c := range characters {
		list.Data = append(list.Data, toGQLCharacter(c))
	}
	if list.Data == nil {
		list.Data = []*model.Character{}
	}
	return list, nil
}

// CharactersByAnime is the resolver for the charactersByAnime field.
func (r *queryResolver) CharactersByAnime(ctx context.Context, animeID string, page *int, limit *int) (*model.CharacterList, error) {
	uid, err := parseID(animeID)
	if err != nil {
		return nil, fmt.Errorf("invalid anime ID: %s", animeID)
	}
	p, l := paginationArgs(page, limit)
	characters, total, err := r.CharacterService.GetCharactersByAnime(ctx, uid, p, l)
	if err != nil {
		return nil, err
	}
	list := &model.CharacterList{Total: int(total)}
	for _, c := range characters {
		list.Data = append(list.Data, toGQLCharacter(c))
	}
	if list.Data == nil {
		list.Data = []*model.Character{}
	}
	return list, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
