version: '3.8'
services:
  db:
    image: postgres:14
    container_name: myanimeapi-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myanimeapi
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myanimeapi-api
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=myanimeapi
      - VAULT_ADDR=http://vault:8200 # Pass the Vault address
    depends_on:
      - db
      - vault
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root" # Root token for development
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    command: server -dev
    volumes:
      - vault_data:/vault/file # Persist Vault data

volumes:
  db_data:
  vault_data: