version: '3'
services:
  db:
    image: postgres:14
    container_name: myanimeapi-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myanimeapi
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myanimeapi-api
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  db_data:
