// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Anime struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Description *string    `json:"description,omitempty"`
	Rating      *float64   `json:"rating,omitempty"`
	Episodes    *int       `json:"episodes,omitempty"`
	Status      *string    `json:"status,omitempty"`
	StartDate   *time.Time `json:"startDate,omitempty"`
	EndDate     *time.Time `json:"endDate,omitempty"`
	Genres      []*Genre   `json:"genres,omitempty"`
	Tags        []*Tag     `json:"tags,omitempty"`
}

type AnimeList struct {
	Data  []*Anime `json:"data"`
	Total int      `json:"total"`
}

type AuthPayload struct {
	Token string `json:"token"`
}

type Genre struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Mutation struct {
}

type Query struct {
}

type Tag struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
	IsAdmin  bool   `json:"isAdmin"`
	IsActive bool   `json:"isActive"`
}
