// internal/routes/routes.go
package routes

import (
	"myanimeapi/pkg/handlers"

	_ "myanimeapi/cmd/docs" // This is required to load the docs generated by Swaggo

	"github.com/gorilla/mux"
	httpSwagger "github.com/swaggo/http-swagger"
)

func RegisterRoutes(router *mux.Router) {
	// Register anime routes
	handlers.RegisterAnimeRoutes(router)

	// Register user routes
	handlers.RegisterUserRoutes(router)

	// Register review routes
	handlers.RegisterReviewRoutes(router)

	// Register auth routes
	handlers.RegisterAuthRoutes(router)

	//when the application startup it will run http://localhost:8080/swagger/index.html
	//router.PathPrefix("/swagger/").Handler(httpSwagger.WrapHandler)
	router.PathPrefix("/swagger/").Handler(httpSwagger.Handler(
		httpSwagger.URL("http://localhost:8080/swagger/doc.json"), // Path to swagger.json
	))
}
