// internal/routes/routes.go
// Package routes provides the routing for the application.
// It registers the routes for the different resources.
// It also registers the Swagger documentation.
// It uses the handlers package to handle the requests.
// It uses the mux package to handle the routing.
// It uses the httpSwagger package to serve the Swagger documentation.
// It uses the swaggo package to generate the Swagger documentation.
// It uses the gorilla/mux package to handle the routing.
package routes

import (
	"log"
	"myanimeapi/pkg/handlers"
	"myanimeapi/pkg/middleware"
	"net/http"

	_ "myanimeapi/cmd/docs" // This is required to load the docs generated by Swaggo

	"github.com/gorilla/mux"
	httpSwagger "github.com/swaggo/http-swagger"
)

// RegisterRoutes registers all routes for the application
func RegisterRoutes(router *mux.Router, swaggerURL string, animeHandler *handlers.AnimeHandler, userHandler *handlers.UserHandler, reviewHandler *handlers.ReviewHandler, authHandler *handlers.AuthHandler) {
	// Create a new rate limiter with a limit of 100 requests per minute
	rateLimiter := middleware.NewRateLimiter()

	// Apply rate limiting middleware
	router.Use(rateLimiter.RateLimitMiddleware)

	// Apply global middleware
	router.Use(middleware.LoggingMiddleware)
	log.Println("Global middleware registered")

	// Create a versioned subrouter
	v1Router := router.PathPrefix("/v1").Subrouter()

	// Health check endpoint
	v1Router.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		if _, err := w.Write([]byte("OK")); err != nil {
			http.Error(w, "Failed to write response", http.StatusInternalServerError)
			return
		}
	}).Methods("GET")
	log.Println("Health check endpoint registered")

	// Register anime routes
	animeHandler.RegisterAnimeRoutes(v1Router)
	log.Println("Anime routes registered")

	// Register user routes
	userHandler.RegisterUserRoutes(v1Router)
	log.Println("User routes registered")

	// Register review routes
	reviewHandler.RegisterReviewRoutes(v1Router)
	log.Println("Review routes registered")

	// Register auth routes
	authHandler.RegisterAuthRoutes(v1Router)
	log.Println("Auth routes registered")

	// Register Swagger documentation
	router.PathPrefix("/swagger/").Handler(httpSwagger.Handler(
		httpSwagger.URL(swaggerURL), // Path to swagger.json
	))
	log.Println("Swagger documentation registered")
}
