// internal/routes/routes.go
// Package routes provides the routing for the application.
// It registers routes for different resources, such as anime, users, reviews, and authentication.
// It also serves Swagger documentation for API endpoints.
// The package uses the `gorilla/mux` package for routing and the `http-swagger` package to serve Swagger documentation.
package routes

import (
	"log"
	"myanimeapi/pkg/handlers"
	"myanimeapi/pkg/middleware"
	"net/http"

	_ "myanimeapi/cmd/docs" // This is required to load the docs generated by Swaggo

	"github.com/gorilla/mux"
	httpSwagger "github.com/swaggo/http-swagger"
)

// RegisterRoutes registers all routes for the application.
// It sets up routes for health checks, anime, users, reviews, and authentication.
// It also applies global middleware, such as logging and rate limiting.
//
// Parameters:
//   - router: A pointer to a `mux.Router` instance to register routes.
//   - swaggerURL: The URL path to the Swagger JSON file.
//   - animeHandler: A pointer to an `AnimeHandler` instance for anime-related routes.
//   - userHandler: A pointer to a `UserHandler` instance for user-related routes.
//   - reviewHandler: A pointer to a `ReviewHandler` instance for review-related routes.
//   - authHandler: A pointer to an `AuthHandler` instance for authentication-related routes.
//
// Example usage:
//
//	router := mux.NewRouter()
//	RegisterRoutes(router, "/swagger/doc.json", animeHandler, userHandler, reviewHandler, authHandler)
//	http.ListenAndServe(":8080", router)
func RegisterRoutes(router *mux.Router, swaggerURL string, animeHandler *handlers.AnimeHandler, userHandler *handlers.UserHandler, reviewHandler *handlers.ReviewHandler, authHandler *handlers.AuthHandler) {
	// Create a new rate limiter with a limit of 100 requests per minute
	rateLimiter := middleware.NewRateLimiter()

	// Apply rate limiting middleware
	router.Use(rateLimiter.RateLimitMiddleware)

	// Apply global middleware
	router.Use(middleware.LoggingMiddleware)
	log.Println("Global middleware registered")

	// Health check endpoint
	router.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		if _, err := w.Write([]byte("OK")); err != nil {
			http.Error(w, "Failed to write response", http.StatusInternalServerError)
			return
		}
	}).Methods("GET")
	log.Println("Health check endpoint registered")

	// Register anime routes
	animeHandler.RegisterAnimeRoutes(router)
	log.Println("Anime routes registered")

	// Register user routes
	userHandler.RegisterUserRoutes(router)
	log.Println("User routes registered")

	// Register review routes
	reviewHandler.RegisterReviewRoutes(router)
	log.Println("Review routes registered")

	// Register auth routes
	authHandler.RegisterAuthRoutes(router)
	log.Println("Auth routes registered")

	// Register Swagger documentation
	router.PathPrefix("/swagger/").Handler(httpSwagger.Handler(
		httpSwagger.URL(swaggerURL), // Path to swagger.json
	))
	log.Println("Swagger documentation registered")
}
