// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@myanimeapi.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/reviews/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete a review by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reviews"
                ],
                "summary": "Delete a review by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Review ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Invalid ID format",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Review not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Failed to delete review",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/anime": {
            "get": {
                "security": [
                    {
                        "": [
                            ""
                        ]
                    }
                ],
                "description": "Retrieve a list of all anime entries",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "anime"
                ],
                "summary": "Get all anime entries",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Anime"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to retrieve anime",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create a new anime entry with the provided data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "anime"
                ],
                "summary": "Create a new anime",
                "parameters": [
                    {
                        "description": "Anime data",
                        "name": "anime",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AnimeCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.AnimeResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid input or missing required fields",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to create anime",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/anime/{id}": {
            "get": {
                "security": [
                    {
                        "": [
                            ""
                        ]
                    }
                ],
                "description": "Retrieve an anime by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "anime"
                ],
                "summary": "Get an anime by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Anime ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Anime"
                        }
                    },
                    "400": {
                        "description": "Invalid ID format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Anime not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to retrieve anime",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update an existing anime entry with the provided data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "anime"
                ],
                "summary": "Update an anime",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Anime ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated anime data",
                        "name": "anime",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Anime"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Anime"
                        }
                    },
                    "400": {
                        "description": "Invalid input or ID format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Anime not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to update anime",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete an anime entry by its ID",
                "tags": [
                    "anime"
                ],
                "summary": "Delete an anime",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Anime ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Invalid ID format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Anime not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to delete anime",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/anime/{id}/reviews": {
            "get": {
                "security": [
                    {
                        "": [
                            ""
                        ]
                    }
                ],
                "description": "Retrieve paginated reviews for an anime by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "anime"
                ],
                "summary": "Get paginated reviews for an anime",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Anime ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of items per page (default: 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Review"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid ID format or pagination parameters",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to retrieve reviews",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/auth/authenticate": {
            "post": {
                "security": [
                    {
                        "": [
                            ""
                        ]
                    }
                ],
                "description": "Authenticate a user and return a JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Authenticate a user",
                "parameters": [
                    {
                        "description": "User credentials",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserCredentials"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns a JWT token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "User not found or invalid credentials",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to generate token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/auth/register": {
            "post": {
                "security": [
                    {
                        "": [
                            ""
                        ]
                    }
                ],
                "description": "Register a new user with the provided data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "User registration data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "400": {
                        "description": "Invalid input or missing required fields",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "User with this username or email already exists",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to hash password or create user",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/reviews": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create a new review for an anime",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reviews"
                ],
                "summary": "Create a new review",
                "parameters": [
                    {
                        "description": "Review data",
                        "name": "review",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ReviewCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Review"
                        }
                    },
                    "400": {
                        "description": "Invalid input or missing required fields",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Anime or user not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to create review",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/reviews/{id}": {
            "get": {
                "security": [
                    {
                        "": [
                            ""
                        ]
                    }
                ],
                "description": "Retrieve a review by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reviews"
                ],
                "summary": "Get a review by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Review ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ReviewResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid ID format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Review not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to retrieve review",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update a review with the input payload",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reviews"
                ],
                "summary": "Update a review by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Review ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated review data",
                        "name": "review",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ReviewCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ReviewResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid input or ID format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Review not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to update review",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/users": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a paginated list of all users. Requires admin privileges.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get all users (admin only)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of items per page (default: 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.User"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid pagination parameters",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Access denied",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to retrieve users",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "": [
                            ""
                        ]
                    }
                ],
                "description": "Create a new user with the provided data.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create a new user",
                "parameters": [
                    {
                        "description": "User data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid input or missing required fields",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "User with this username or email already exists",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to create user",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/users/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a user by their ID. Requires authentication.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get a user by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "400": {
                        "description": "Invalid ID format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to retrieve user",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update an existing user with the provided data. Requires authentication.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update a user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated user data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid input or ID format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to update user",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete a user by their ID. Requires authentication.",
                "tags": [
                    "users"
                ],
                "summary": "Delete a user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Invalid ID format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to delete user",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Anime": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "created_at": {
                    "description": "Timestamp when the anime was created",
                    "type": "string",
                    "example": "2025-02-20T19:27:00Z"
                },
                "description": {
                    "description": "Description of the anime",
                    "type": "string",
                    "maxLength": 500,
                    "example": "A story about ninjas."
                },
                "id": {
                    "description": "Unique identifier for the anime",
                    "type": "integer",
                    "example": 1
                },
                "rating": {
                    "description": "Average rating of the anime",
                    "type": "number",
                    "maximum": 10,
                    "minimum": 0,
                    "example": 8.5
                },
                "reviews": {
                    "description": "List of reviews for the anime (omitted unless necessary)",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Review"
                    }
                },
                "title": {
                    "description": "Title of the anime",
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3,
                    "example": "Naruto"
                },
                "updated_at": {
                    "description": "Timestamp when the anime was last updated",
                    "type": "string",
                    "example": "2025-02-20T19:27:00Z"
                }
            }
        },
        "models.AnimeCreateRequest": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "description": {
                    "description": "Description of the anime (optional, max 500 characters)",
                    "type": "string",
                    "maxLength": 500,
                    "example": "A story about ninjas."
                },
                "rating": {
                    "description": "Rating of the anime (0-10)",
                    "type": "number",
                    "maximum": 10,
                    "minimum": 0,
                    "example": 8.5
                },
                "title": {
                    "description": "Title of the anime (required, 3-100 characters)",
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3,
                    "example": "Naruto"
                }
            }
        },
        "models.AnimeResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "Timestamp when the anime was created",
                    "type": "string",
                    "example": "2025-02-20T19:27:00Z"
                },
                "description": {
                    "description": "Description of the anime",
                    "type": "string",
                    "example": "A story about ninjas."
                },
                "id": {
                    "description": "Unique identifier for the anime",
                    "type": "integer",
                    "example": 1
                },
                "rating": {
                    "description": "Average rating of the anime",
                    "type": "number",
                    "example": 8.5
                },
                "title": {
                    "description": "Title of the anime",
                    "type": "string",
                    "example": "Naruto"
                },
                "updated_at": {
                    "description": "Timestamp when the anime was last updated",
                    "type": "string",
                    "example": "2025-02-20T19:27:00Z"
                }
            }
        },
        "models.Review": {
            "type": "object",
            "required": [
                "content",
                "rating"
            ],
            "properties": {
                "animeId": {
                    "description": "Anime ID with cascade delete constraint",
                    "type": "integer",
                    "example": 1
                },
                "content": {
                    "description": "Review content",
                    "type": "string",
                    "maxLength": 500,
                    "example": "This anime is amazing!"
                },
                "created_at": {
                    "description": "Creation timestamp",
                    "type": "string",
                    "example": "2025-02-20T19:27:00Z"
                },
                "id": {
                    "description": "Review ID",
                    "type": "integer",
                    "example": 1
                },
                "rating": {
                    "description": "Rating (0-10)",
                    "type": "integer",
                    "maximum": 10,
                    "minimum": 0,
                    "example": 9
                },
                "updated_at": {
                    "description": "Update timestamp",
                    "type": "string",
                    "example": "2025-02-20T19:27:00Z"
                },
                "userId": {
                    "description": "User ID",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "models.ReviewCreateRequest": {
            "type": "object",
            "required": [
                "animeId",
                "content",
                "rating",
                "userId"
            ],
            "properties": {
                "animeId": {
                    "description": "ID of the anime being reviewed (required)",
                    "type": "integer",
                    "example": 1
                },
                "content": {
                    "description": "Content of the review (required, max 500 characters)",
                    "type": "string",
                    "maxLength": 500,
                    "example": "This anime is amazing!"
                },
                "rating": {
                    "description": "Rating given in the review (0-10, required)",
                    "type": "integer",
                    "maximum": 10,
                    "minimum": 0,
                    "example": 9
                },
                "userId": {
                    "description": "ID of the user creating the review (required)",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "models.ReviewResponse": {
            "type": "object",
            "properties": {
                "anime": {
                    "description": "Anime details",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.AnimeResponse"
                        }
                    ]
                },
                "animeId": {
                    "description": "ID of the anime being reviewed",
                    "type": "integer",
                    "example": 1
                },
                "content": {
                    "description": "Content of the review",
                    "type": "string",
                    "example": "This anime is amazing!"
                },
                "created_at": {
                    "description": "Timestamp when the review was created",
                    "type": "string",
                    "example": "2025-02-20T19:27:00Z"
                },
                "id": {
                    "description": "Unique identifier for the review",
                    "type": "integer",
                    "example": 1
                },
                "rating": {
                    "description": "Rating given in the review (0-10)",
                    "type": "integer",
                    "example": 9
                },
                "updated_at": {
                    "description": "Timestamp when the review was last updated",
                    "type": "string",
                    "example": "2025-02-20T19:27:00Z"
                },
                "user": {
                    "description": "User details",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.UserResponse"
                        }
                    ]
                },
                "userId": {
                    "description": "ID of the user who created the review",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "models.User": {
            "type": "object",
            "required": [
                "email",
                "username"
            ],
            "properties": {
                "created_at": {
                    "description": "Timestamp when the user was created",
                    "type": "string",
                    "example": "2025-02-20T19:27:00Z"
                },
                "email": {
                    "description": "Unique Email address of the user (omitted unless necessary)",
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 5,
                    "example": "john@example.com"
                },
                "id": {
                    "description": "Unique identifier for the user",
                    "type": "integer",
                    "example": 1
                },
                "is_admin": {
                    "description": "Indicates if the user has admin privileges",
                    "type": "boolean",
                    "example": false
                },
                "reviews": {
                    "description": "List of reviews created by the user (omitted unless necessary)",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Review"
                    }
                },
                "updated_at": {
                    "description": "Timestamp when the user was last updated",
                    "type": "string",
                    "example": "2025-02-20T19:27:00Z"
                },
                "username": {
                    "description": "Unique username for the user",
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3,
                    "example": "john_doe"
                }
            }
        },
        "models.UserCreateRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "description": "Email address for the new user (required, valid email format, 5-100 characters)",
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 5,
                    "example": "john@example.com"
                },
                "password": {
                    "description": "Password for the new user (required, 5-100 characters)",
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 5,
                    "example": "password123"
                },
                "username": {
                    "description": "Username for the new user (required, 3-50 characters)",
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3,
                    "example": "john_doe"
                }
            }
        },
        "models.UserCredentials": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "Password for authentication",
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 5,
                    "example": "password123"
                },
                "username": {
                    "description": "Username for authentication",
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3,
                    "example": "john_doe"
                }
            }
        },
        "models.UserResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "Timestamp when the user was created",
                    "type": "string",
                    "example": "2025-02-20T19:27:00Z"
                },
                "id": {
                    "description": "Unique identifier for the user",
                    "type": "integer",
                    "example": 1
                },
                "is_admin": {
                    "description": "Indicates if the user has admin privileges",
                    "type": "boolean",
                    "example": false
                },
                "updated_at": {
                    "description": "Timestamp when the user was last updated",
                    "type": "string",
                    "example": "2025-02-20T19:27:00Z"
                },
                "username": {
                    "description": "Username of the user",
                    "type": "string",
                    "example": "john_doe"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "Use the format \"Bearer \u003cJWT_TOKEN\u003e\". Example: \"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/v1",
	Schemes:          []string{"http"},
	Title:            "MyAnimeAPI",
	Description:      "This is a sample API for managing anime and reviews.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
