// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@myanimeapi.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/analytics": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Admin analytics",
                "responses": {}
            }
        },
        "/admin/stats": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Admin dashboard stats",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httphandler.AdminStats"
                        }
                    }
                }
            }
        },
        "/admin/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "List all users (admin)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size (default 20, max 100)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/admin/users/{id}/role": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Update user role (admin)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New role",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httphandler.UpdateRoleRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/animes": {
            "get": {
                "description": "Returns a paginated, filterable, sortable list of animes.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "anime"
                ],
                "summary": "List animes",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "Airing",
                            "Completed",
                            "Upcoming"
                        ],
                        "type": "string",
                        "description": "Filter by status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by exact genre name (single)",
                        "name": "genre",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by multiple genres, comma-separated (AND logic)",
                        "name": "genres",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by exact tag name (single)",
                        "name": "tag",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by multiple tags, comma-separated (AND logic)",
                        "name": "tags",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Minimum rating (0–10)",
                        "name": "rating_min",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Maximum rating (0–10)",
                        "name": "rating_max",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Minimum episode count",
                        "name": "episodes_min",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Maximum episode count",
                        "name": "episodes_max",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Start-date year lower bound (inclusive)",
                        "name": "year_from",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Start-date year upper bound (inclusive)",
                        "name": "year_to",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "title",
                            "rating",
                            "episodes",
                            "created_at",
                            "start_date"
                        ],
                        "type": "string",
                        "description": "Sort field",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "description": "Sort direction",
                        "name": "order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "data": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/models.AnimeResponse"
                                    }
                                },
                                "limit": {
                                    "type": "integer"
                                },
                                "page": {
                                    "type": "integer"
                                },
                                "total": {
                                    "type": "integer"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid filter or pagination",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new anime with the provided details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "anime"
                ],
                "summary": "Create a new anime",
                "parameters": [
                    {
                        "description": "Anime details",
                        "name": "anime",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AnimeCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.AnimeResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to create anime",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/animes/search": {
            "get": {
                "description": "Returns animes whose title contains the given string. Supports sort and pagination.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "anime"
                ],
                "summary": "Search animes by title",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Title substring to search for",
                        "name": "title",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "title",
                            "rating",
                            "episodes",
                            "created_at",
                            "start_date"
                        ],
                        "type": "string",
                        "description": "Sort field",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "description": "Sort direction",
                        "name": "order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "data": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/models.AnimeResponse"
                                    }
                                },
                                "limit": {
                                    "type": "integer"
                                },
                                "page": {
                                    "type": "integer"
                                },
                                "total": {
                                    "type": "integer"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/animes/{animeId}/characters": {
            "get": {
                "description": "Returns the cast of a given anime",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "characters"
                ],
                "summary": "Get characters for an anime",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Anime ID",
                        "name": "animeId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.CharacterListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "characters"
                ],
                "summary": "Add characters to anime",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Anime ID",
                        "name": "animeId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Character IDs",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AnimeCharacterRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/animes/{animeId}/characters/{characterId}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "characters"
                ],
                "summary": "Remove character from anime",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Anime ID",
                        "name": "animeId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Character ID",
                        "name": "characterId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/authenticate": {
            "post": {
                "description": "Authenticate a user and return a JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Authenticate a user",
                "parameters": [
                    {
                        "description": "User credentials",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserCredentials"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Register a new user with the provided credentials",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "User registration information",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/characters": {
            "get": {
                "description": "Get a paginated list of all characters",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "characters"
                ],
                "summary": "Get all characters",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.CharacterListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new character entry",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "characters"
                ],
                "summary": "Create character",
                "parameters": [
                    {
                        "description": "Character data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CharacterCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.CharacterResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/characters/search": {
            "get": {
                "description": "Find characters whose name contains the given query",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "characters"
                ],
                "summary": "Search characters by name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name substring to search",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.CharacterListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/characters/{id}": {
            "get": {
                "description": "Retrieve a character and its anime appearances",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "characters"
                ],
                "summary": "Get character by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Character ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.CharacterResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update character fields",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "characters"
                ],
                "summary": "Update character",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Character ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CharacterUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.CharacterResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "characters"
                ],
                "summary": "Delete character",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Character ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/etl/sync": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Fetches the top-anime list from Jikan API (jikan.moe) and upserts\neach entry into the local database, including genres, tags, cover\nimages, and MyAnimeList scores.  Admin-only.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "etl"
                ],
                "summary": "Sync anime data from Jikan / MyAnimeList",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pages to fetch from Jikan (1 page = 25 anime, default 5, max 20)",
                        "name": "pages",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.SyncResult"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/favorites": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all favorites for the authenticated user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "favorites"
                ],
                "summary": "Get user's favorites",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Favorite"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/favorites/{anime_id}": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Add an anime to the authenticated user's favorites",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "favorites"
                ],
                "summary": "Add anime to favorites",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Anime ID",
                        "name": "anime_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Favorite"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Remove an anime from the authenticated user's favorites",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "favorites"
                ],
                "summary": "Remove anime from favorites",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Anime ID",
                        "name": "anime_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/genres": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new genre with the provided details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "genres"
                ],
                "summary": "Create a new genre",
                "parameters": [
                    {
                        "description": "Genre details",
                        "name": "genre",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Genre"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.GenreResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Genre name already exists",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to create genre",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tags": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new tag with the provided details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "Create a new tag",
                "parameters": [
                    {
                        "description": "Tag details",
                        "name": "tag",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TagCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.TagResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Tag name already exists",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to create tag",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/watchlist": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all watchlist entries for the authenticated user, with a grouped view",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "watchlist"
                ],
                "summary": "Get user's watchlist",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httphandler.watchlistResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/watchlist/{animeId}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Add an anime to the authenticated user's watchlist or update its status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "watchlist"
                ],
                "summary": "Add or update watchlist entry",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Anime ID",
                        "name": "animeId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Watchlist status",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.WatchlistUpsertRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.WatchlistEntryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Remove an anime from the authenticated user's watchlist",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "watchlist"
                ],
                "summary": "Remove watchlist entry",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Anime ID",
                        "name": "animeId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "errors.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "object",
                    "properties": {
                        "code": {
                            "description": "A unique error code for categorization.",
                            "type": "string"
                        },
                        "context": {
                            "description": "Additional context fields for debugging.",
                            "type": "object",
                            "additionalProperties": true
                        },
                        "details": {
                            "description": "Additional context or details about the error.",
                            "type": "string"
                        },
                        "message": {
                            "description": "A human-readable error message.",
                            "type": "string"
                        }
                    }
                }
            }
        },
        "httphandler.AdminStats": {
            "type": "object",
            "properties": {
                "anime_total": {
                    "type": "integer"
                },
                "favorites_total": {
                    "type": "integer"
                },
                "genres_total": {
                    "type": "integer"
                },
                "reviews_total": {
                    "type": "integer"
                },
                "tags_total": {
                    "type": "integer"
                },
                "users_total": {
                    "type": "integer"
                },
                "with_cover_total": {
                    "type": "integer"
                }
            }
        },
        "httphandler.UpdateRoleRequest": {
            "type": "object",
            "required": [
                "role"
            ],
            "properties": {
                "role": {
                    "type": "string"
                }
            }
        },
        "httphandler.watchlistGrouped": {
            "type": "object",
            "additionalProperties": {
                "type": "array",
                "items": {
                    "$ref": "#/definitions/models.WatchlistEntryResponse"
                }
            }
        },
        "httphandler.watchlistResponse": {
            "type": "object",
            "properties": {
                "entries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.WatchlistEntryResponse"
                    }
                },
                "grouped": {
                    "$ref": "#/definitions/httphandler.watchlistGrouped"
                }
            }
        },
        "models.Anime": {
            "type": "object",
            "properties": {
                "characters": {
                    "description": "Associated characters",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Character"
                    }
                },
                "cover_url": {
                    "description": "Cover image URL (populated by ETL)",
                    "type": "string",
                    "example": "https://cdn.myanimelist.net/…"
                },
                "created_at": {
                    "description": "Timestamp when the anime was added",
                    "type": "string",
                    "example": "2025-02-20T19:27:00Z"
                },
                "description": {
                    "description": "Description of the anime",
                    "type": "string",
                    "example": "A story about ninjas."
                },
                "end_date": {
                    "description": "Date when the anime finished airing",
                    "type": "string",
                    "example": "2007-02-08T00:00:00Z"
                },
                "episodes": {
                    "description": "Number of episodes",
                    "type": "integer",
                    "example": 220
                },
                "genres": {
                    "description": "Associated genres",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Genre"
                    }
                },
                "id": {
                    "description": "Unique identifier for the anime",
                    "type": "integer",
                    "example": 1
                },
                "mal_id": {
                    "description": "MyAnimeList ID (used for ETL deduplication)",
                    "type": "integer",
                    "example": 20
                },
                "rating": {
                    "description": "Average rating of the anime",
                    "type": "number",
                    "example": 8.5
                },
                "reviews": {
                    "description": "Associated reviews",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Review"
                    }
                },
                "start_date": {
                    "description": "Date when the anime started airing",
                    "type": "string",
                    "example": "2002-10-03T00:00:00Z"
                },
                "status": {
                    "description": "Current status of the anime",
                    "type": "string",
                    "example": "Completed"
                },
                "tags": {
                    "description": "Associated tags",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Tag"
                    }
                },
                "title": {
                    "description": "Title of the anime",
                    "type": "string",
                    "example": "Naruto"
                },
                "updated_at": {
                    "description": "Timestamp when the anime was last updated",
                    "type": "string",
                    "example": "2025-02-20T19:27:00Z"
                }
            }
        },
        "models.AnimeCharacterRequest": {
            "type": "object",
            "required": [
                "character_ids"
            ],
            "properties": {
                "character_ids": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        1,
                        2,
                        3
                    ]
                }
            }
        },
        "models.AnimeCreateRequest": {
            "type": "object",
            "required": [
                "episodes",
                "rating",
                "start_date",
                "status",
                "title"
            ],
            "properties": {
                "description": {
                    "description": "Description of the anime",
                    "type": "string",
                    "example": "A story about ninjas."
                },
                "end_date": {
                    "description": "Date when the anime finished airing",
                    "type": "string",
                    "example": "2007-02-08T00:00:00Z"
                },
                "episodes": {
                    "description": "Number of episodes",
                    "type": "integer",
                    "example": 220
                },
                "genre_ids": {
                    "description": "IDs of genres to associate with the anime",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        1,
                        2,
                        3
                    ]
                },
                "rating": {
                    "description": "Initial rating for the anime",
                    "type": "number",
                    "maximum": 10,
                    "minimum": 0,
                    "example": 8.5
                },
                "start_date": {
                    "description": "Date when the anime started airing",
                    "type": "string",
                    "example": "2002-10-03T00:00:00Z"
                },
                "status": {
                    "description": "Current status of the anime",
                    "type": "string",
                    "example": "Completed"
                },
                "tag_ids": {
                    "description": "IDs of tags to associate with the anime",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        1,
                        2,
                        3
                    ]
                },
                "title": {
                    "description": "Title of the anime",
                    "type": "string",
                    "example": "Naruto"
                }
            }
        },
        "models.AnimeResponse": {
            "type": "object",
            "properties": {
                "characters": {
                    "description": "Associated characters",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.CharacterResponse"
                    }
                },
                "cover_url": {
                    "description": "Cover image URL",
                    "type": "string",
                    "example": "https://cdn.myanimelist.net/images/…"
                },
                "created_at": {
                    "description": "Timestamp when the anime was added",
                    "type": "string",
                    "example": "2025-02-20T19:27:00Z"
                },
                "description": {
                    "description": "Description of the anime",
                    "type": "string",
                    "example": "A story about ninjas."
                },
                "end_date": {
                    "description": "Date when the anime finished airing",
                    "type": "string",
                    "example": "2007-02-08T00:00:00Z"
                },
                "episodes": {
                    "description": "Number of episodes",
                    "type": "integer",
                    "example": 220
                },
                "genres": {
                    "description": "Associated genres",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Genre"
                    }
                },
                "id": {
                    "description": "Unique identifier for the anime",
                    "type": "integer",
                    "example": 1
                },
                "mal_id": {
                    "description": "MyAnimeList ID",
                    "type": "integer",
                    "example": 20
                },
                "rating": {
                    "description": "Average rating of the anime",
                    "type": "number",
                    "example": 8.5
                },
                "reviews": {
                    "description": "Associated reviews (includes username)",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.AnimeReviewEntry"
                    }
                },
                "start_date": {
                    "description": "Date when the anime started airing",
                    "type": "string",
                    "example": "2002-10-03T00:00:00Z"
                },
                "status": {
                    "description": "Current status of the anime",
                    "type": "string",
                    "example": "Completed"
                },
                "tags": {
                    "description": "Associated tags",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Tag"
                    }
                },
                "title": {
                    "description": "Title of the anime",
                    "type": "string",
                    "example": "Naruto"
                },
                "updated_at": {
                    "description": "Timestamp when the anime was last updated",
                    "type": "string",
                    "example": "2025-02-20T19:27:00Z"
                }
            }
        },
        "models.AnimeReviewEntry": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "rating": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.Character": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "animes": {
                    "description": "Anime appearances",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Anime"
                    }
                },
                "created_at": {
                    "description": "Creation timestamp",
                    "type": "string",
                    "example": "2025-02-20T19:27:00Z"
                },
                "deleted_at": {
                    "description": "Soft delete timestamp",
                    "type": "string",
                    "example": "2025-02-20T19:27:00Z"
                },
                "description": {
                    "description": "Brief description",
                    "type": "string",
                    "maxLength": 1000,
                    "example": "The main protagonist."
                },
                "id": {
                    "description": "Unique identifier",
                    "type": "integer",
                    "example": 1
                },
                "image_url": {
                    "description": "Image URL",
                    "type": "string",
                    "example": "https://cdn.example.com/naruto.jpg"
                },
                "name": {
                    "description": "Character name",
                    "type": "string",
                    "maxLength": 150,
                    "example": "Naruto Uzumaki"
                },
                "updated_at": {
                    "description": "Update timestamp",
                    "type": "string",
                    "example": "2025-02-20T19:27:00Z"
                },
                "voice_actor": {
                    "description": "Voice actor name",
                    "type": "string",
                    "maxLength": 150,
                    "example": "Junko Takeuchi"
                }
            }
        },
        "models.CharacterCreateRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 1000,
                    "example": "The main protagonist."
                },
                "image_url": {
                    "type": "string",
                    "example": "https://cdn.example.com/naruto.jpg"
                },
                "name": {
                    "type": "string",
                    "maxLength": 150,
                    "example": "Naruto Uzumaki"
                },
                "voice_actor": {
                    "type": "string",
                    "maxLength": 150,
                    "example": "Junko Takeuchi"
                }
            }
        },
        "models.CharacterListResponse": {
            "type": "object",
            "properties": {
                "characters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.CharacterResponse"
                    }
                },
                "limit": {
                    "type": "integer",
                    "example": 10
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "total": {
                    "type": "integer",
                    "example": 100
                }
            }
        },
        "models.CharacterResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "The main protagonist."
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "image_url": {
                    "type": "string",
                    "example": "https://cdn.example.com/naruto.jpg"
                },
                "name": {
                    "type": "string",
                    "example": "Naruto Uzumaki"
                },
                "voice_actor": {
                    "type": "string",
                    "example": "Junko Takeuchi"
                }
            }
        },
        "models.CharacterUpdateRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 1000,
                    "example": "The main protagonist."
                },
                "image_url": {
                    "type": "string",
                    "example": "https://cdn.example.com/naruto.jpg"
                },
                "name": {
                    "type": "string",
                    "maxLength": 150,
                    "example": "Naruto Uzumaki"
                },
                "voice_actor": {
                    "type": "string",
                    "maxLength": 150,
                    "example": "Junko Takeuchi"
                }
            }
        },
        "models.Favorite": {
            "type": "object",
            "properties": {
                "anime": {
                    "description": "Associated anime details",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Anime"
                        }
                    ]
                },
                "anime_id": {
                    "description": "ID of the favorited anime",
                    "type": "integer",
                    "example": 1
                },
                "created_at": {
                    "description": "Timestamp when the favorite was created",
                    "type": "string",
                    "example": "2025-02-20T19:27:00Z"
                },
                "id": {
                    "description": "Unique identifier for the favorite entry",
                    "type": "integer",
                    "example": 1
                },
                "updated_at": {
                    "description": "Timestamp when the favorite was last updated",
                    "type": "string",
                    "example": "2025-02-20T19:27:00Z"
                },
                "user": {
                    "description": "Associated user details",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.User"
                        }
                    ]
                },
                "user_id": {
                    "description": "ID of the user who favorited the anime",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "models.Genre": {
            "type": "object",
            "properties": {
                "anime": {
                    "description": "Associated anime entries",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Anime"
                    }
                },
                "created_at": {
                    "description": "Creation timestamp",
                    "type": "string",
                    "example": "2025-02-20T19:27:00Z"
                },
                "deleted_at": {
                    "description": "Soft delete timestamp",
                    "type": "string",
                    "example": "2025-02-20T19:27:00Z"
                },
                "id": {
                    "description": "Unique identifier for the genre",
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "description": "Name of the genre",
                    "type": "string",
                    "example": "Action"
                },
                "updated_at": {
                    "description": "Update timestamp",
                    "type": "string",
                    "example": "2025-02-20T19:27:00Z"
                }
            }
        },
        "models.GenreResponse": {
            "type": "object",
            "properties": {
                "anime": {
                    "description": "Associated anime entries",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Anime"
                    }
                },
                "id": {
                    "description": "Unique identifier for the genre",
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "description": "Name of the genre",
                    "type": "string",
                    "example": "Action"
                }
            }
        },
        "models.JSON": {
            "type": "object",
            "additionalProperties": true
        },
        "models.MediaAttachment": {
            "type": "object",
            "required": [
                "type",
                "url"
            ],
            "properties": {
                "created_at": {
                    "description": "Creation timestamp",
                    "type": "string",
                    "example": "2025-02-20T19:27:00Z"
                },
                "id": {
                    "description": "Media attachment ID",
                    "type": "integer",
                    "example": 1
                },
                "review_id": {
                    "description": "Review ID with cascade delete constraint",
                    "type": "integer",
                    "example": 1
                },
                "type": {
                    "description": "Type of media (image or video)",
                    "type": "string",
                    "enum": [
                        "image",
                        "video"
                    ],
                    "example": "image"
                },
                "updated_at": {
                    "description": "Update timestamp",
                    "type": "string",
                    "example": "2025-02-20T19:27:00Z"
                },
                "url": {
                    "description": "URL to the media file",
                    "type": "string",
                    "example": "https://example.com/image.jpg"
                }
            }
        },
        "models.Response": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Data payload (can be any type)"
                },
                "message": {
                    "description": "Message describing the result",
                    "type": "string",
                    "example": "Operation successful"
                },
                "status": {
                    "description": "Status of the response (success, error)",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "models.Review": {
            "type": "object",
            "required": [
                "content",
                "rating"
            ],
            "properties": {
                "animeId": {
                    "description": "Anime ID with cascade delete constraint",
                    "type": "integer",
                    "example": 1
                },
                "content": {
                    "description": "Review content",
                    "type": "string",
                    "maxLength": 500,
                    "example": "This anime is amazing!"
                },
                "created_at": {
                    "description": "Creation timestamp",
                    "type": "string",
                    "example": "2025-02-20T19:27:00Z"
                },
                "id": {
                    "description": "Review ID",
                    "type": "integer",
                    "example": 1
                },
                "media_attachments": {
                    "description": "Associated media attachments",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MediaAttachment"
                    }
                },
                "rating": {
                    "description": "Rating (0-10)",
                    "type": "integer",
                    "maximum": 10,
                    "minimum": 0,
                    "example": 9
                },
                "updated_at": {
                    "description": "Update timestamp",
                    "type": "string",
                    "example": "2025-02-20T19:27:00Z"
                },
                "userId": {
                    "description": "User ID",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "models.Tag": {
            "type": "object",
            "properties": {
                "anime": {
                    "description": "Associated anime entries",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Anime"
                    }
                },
                "created_at": {
                    "description": "Creation timestamp",
                    "type": "string",
                    "example": "2025-02-20T19:27:00Z"
                },
                "deleted_at": {
                    "description": "Soft delete timestamp",
                    "type": "string",
                    "example": "2025-02-20T19:27:00Z"
                },
                "id": {
                    "description": "Unique identifier for the tag",
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "description": "Name of the tag",
                    "type": "string",
                    "example": "Ninja"
                },
                "updated_at": {
                    "description": "Update timestamp",
                    "type": "string",
                    "example": "2025-02-20T19:27:00Z"
                }
            }
        },
        "models.TagCreateRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "description": "Name of the tag",
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1,
                    "example": "Action"
                }
            }
        },
        "models.TagResponse": {
            "type": "object",
            "properties": {
                "anime": {
                    "description": "Associated anime entries",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Anime"
                    }
                },
                "id": {
                    "description": "Unique identifier for the tag",
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "description": "Name of the tag",
                    "type": "string",
                    "example": "Ninja"
                }
            }
        },
        "models.User": {
            "type": "object",
            "required": [
                "email",
                "username"
            ],
            "properties": {
                "bio": {
                    "description": "User's biography",
                    "type": "string",
                    "example": "Anime enthusiast"
                },
                "created_at": {
                    "description": "Creation timestamp",
                    "type": "string",
                    "example": "2025-02-20T19:27:00Z"
                },
                "deleted_at": {
                    "description": "Soft delete timestamp",
                    "type": "string",
                    "example": "2025-02-20T19:27:00Z"
                },
                "email": {
                    "description": "Unique Email address of the user",
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 5,
                    "example": "john@example.com"
                },
                "favorites": {
                    "description": "User's favorite anime",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Anime"
                    }
                },
                "genres": {
                    "description": "User's preferred genres",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Genre"
                    }
                },
                "id": {
                    "description": "Unique identifier",
                    "type": "integer",
                    "example": 1
                },
                "is_active": {
                    "description": "Indicates if the user account is active",
                    "type": "boolean",
                    "example": true
                },
                "is_admin": {
                    "description": "Indicates if the user has admin privileges",
                    "type": "boolean",
                    "example": false
                },
                "profile_pic": {
                    "description": "URL to the user's profile picture",
                    "type": "string",
                    "example": "https://example.com/profile.jpg"
                },
                "reviews": {
                    "description": "User's reviews",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Review"
                    }
                },
                "role": {
                    "description": "RBAC role: user | reviewer | admin",
                    "type": "string",
                    "example": "user"
                },
                "social_links": {
                    "description": "User's social media links",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.JSON"
                        }
                    ]
                },
                "updated_at": {
                    "description": "Update timestamp",
                    "type": "string",
                    "example": "2025-02-20T19:27:00Z"
                },
                "username": {
                    "description": "Unique username for the user",
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3,
                    "example": "john_doe"
                }
            }
        },
        "models.UserCredentials": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "Password for authentication",
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 5,
                    "example": "password123"
                },
                "username": {
                    "description": "Username for authentication",
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3,
                    "example": "john_doe"
                }
            }
        },
        "models.WatchlistEntryResponse": {
            "type": "object",
            "properties": {
                "anime": {
                    "$ref": "#/definitions/models.AnimeResponse"
                },
                "anime_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/models.WatchlistStatus"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.WatchlistStatus": {
            "type": "string",
            "enum": [
                "plan_to_watch",
                "watching",
                "completed",
                "dropped",
                "on_hold"
            ],
            "x-enum-varnames": [
                "WatchlistStatusPlanToWatch",
                "WatchlistStatusWatching",
                "WatchlistStatusCompleted",
                "WatchlistStatusDropped",
                "WatchlistStatusOnHold"
            ]
        },
        "models.WatchlistUpsertRequest": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "status": {
                    "$ref": "#/definitions/models.WatchlistStatus"
                }
            }
        },
        "services.SyncResult": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "integer"
                },
                "imported": {
                    "type": "integer"
                },
                "pages": {
                    "type": "integer"
                },
                "skipped": {
                    "type": "integer"
                },
                "updated": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "Use the format \"Bearer \u003cJWT_TOKEN\u003e\". Example: \"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/v1",
	Schemes:          []string{"http"},
	Title:            "MyAnimeAPI",
	Description:      "This is a sample API for managing anime and reviews.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
