// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	models "myanimeapi/api/models"

	mock "github.com/stretchr/testify/mock"
)

// MockFavoriteServiceInterface is an autogenerated mock type for the FavoriteServiceInterface type
type MockFavoriteServiceInterface struct {
	mock.Mock
}

type MockFavoriteServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFavoriteServiceInterface) EXPECT() *MockFavoriteServiceInterface_Expecter {
	return &MockFavoriteServiceInterface_Expecter{mock: &_m.Mock}
}

// AddFavorite provides a mock function with given fields: ctx, userID, animeID
func (_m *MockFavoriteServiceInterface) AddFavorite(ctx context.Context, userID uint, animeID uint) (*models.Favorite, error) {
	ret := _m.Called(ctx, userID, animeID)

	if len(ret) == 0 {
		panic("no return value specified for AddFavorite")
	}

	var r0 *models.Favorite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) (*models.Favorite, error)); ok {
		return rf(ctx, userID, animeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) *models.Favorite); ok {
		r0 = rf(ctx, userID, animeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Favorite)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = rf(ctx, userID, animeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFavoriteServiceInterface_AddFavorite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddFavorite'
type MockFavoriteServiceInterface_AddFavorite_Call struct {
	*mock.Call
}

// AddFavorite is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - animeID uint
func (_e *MockFavoriteServiceInterface_Expecter) AddFavorite(ctx interface{}, userID interface{}, animeID interface{}) *MockFavoriteServiceInterface_AddFavorite_Call {
	return &MockFavoriteServiceInterface_AddFavorite_Call{Call: _e.mock.On("AddFavorite", ctx, userID, animeID)}
}

func (_c *MockFavoriteServiceInterface_AddFavorite_Call) Run(run func(ctx context.Context, userID uint, animeID uint)) *MockFavoriteServiceInterface_AddFavorite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *MockFavoriteServiceInterface_AddFavorite_Call) Return(_a0 *models.Favorite, _a1 error) *MockFavoriteServiceInterface_AddFavorite_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFavoriteServiceInterface_AddFavorite_Call) RunAndReturn(run func(context.Context, uint, uint) (*models.Favorite, error)) *MockFavoriteServiceInterface_AddFavorite_Call {
	_c.Call.Return(run)
	return _c
}

// GetFavorites provides a mock function with given fields: ctx, userID
func (_m *MockFavoriteServiceInterface) GetFavorites(ctx context.Context, userID uint) ([]models.Favorite, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetFavorites")
	}

	var r0 []models.Favorite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]models.Favorite, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []models.Favorite); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Favorite)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFavoriteServiceInterface_GetFavorites_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFavorites'
type MockFavoriteServiceInterface_GetFavorites_Call struct {
	*mock.Call
}

// GetFavorites is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockFavoriteServiceInterface_Expecter) GetFavorites(ctx interface{}, userID interface{}) *MockFavoriteServiceInterface_GetFavorites_Call {
	return &MockFavoriteServiceInterface_GetFavorites_Call{Call: _e.mock.On("GetFavorites", ctx, userID)}
}

func (_c *MockFavoriteServiceInterface_GetFavorites_Call) Run(run func(ctx context.Context, userID uint)) *MockFavoriteServiceInterface_GetFavorites_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockFavoriteServiceInterface_GetFavorites_Call) Return(_a0 []models.Favorite, _a1 error) *MockFavoriteServiceInterface_GetFavorites_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFavoriteServiceInterface_GetFavorites_Call) RunAndReturn(run func(context.Context, uint) ([]models.Favorite, error)) *MockFavoriteServiceInterface_GetFavorites_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveFavorite provides a mock function with given fields: ctx, userID, animeID
func (_m *MockFavoriteServiceInterface) RemoveFavorite(ctx context.Context, userID uint, animeID uint) error {
	ret := _m.Called(ctx, userID, animeID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveFavorite")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) error); ok {
		r0 = rf(ctx, userID, animeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFavoriteServiceInterface_RemoveFavorite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveFavorite'
type MockFavoriteServiceInterface_RemoveFavorite_Call struct {
	*mock.Call
}

// RemoveFavorite is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - animeID uint
func (_e *MockFavoriteServiceInterface_Expecter) RemoveFavorite(ctx interface{}, userID interface{}, animeID interface{}) *MockFavoriteServiceInterface_RemoveFavorite_Call {
	return &MockFavoriteServiceInterface_RemoveFavorite_Call{Call: _e.mock.On("RemoveFavorite", ctx, userID, animeID)}
}

func (_c *MockFavoriteServiceInterface_RemoveFavorite_Call) Run(run func(ctx context.Context, userID uint, animeID uint)) *MockFavoriteServiceInterface_RemoveFavorite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *MockFavoriteServiceInterface_RemoveFavorite_Call) Return(_a0 error) *MockFavoriteServiceInterface_RemoveFavorite_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFavoriteServiceInterface_RemoveFavorite_Call) RunAndReturn(run func(context.Context, uint, uint) error) *MockFavoriteServiceInterface_RemoveFavorite_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFavoriteServiceInterface creates a new instance of MockFavoriteServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFavoriteServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFavoriteServiceInterface {
	mock := &MockFavoriteServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
