// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockPasswordResetServiceInterface is an autogenerated mock type for the PasswordResetServiceInterface type
type MockPasswordResetServiceInterface struct {
	mock.Mock
}

type MockPasswordResetServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPasswordResetServiceInterface) EXPECT() *MockPasswordResetServiceInterface_Expecter {
	return &MockPasswordResetServiceInterface_Expecter{mock: &_m.Mock}
}

// RequestPasswordReset provides a mock function with given fields: ctx, email
func (_m *MockPasswordResetServiceInterface) RequestPasswordReset(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for RequestPasswordReset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPasswordResetServiceInterface_RequestPasswordReset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestPasswordReset'
type MockPasswordResetServiceInterface_RequestPasswordReset_Call struct {
	*mock.Call
}

// RequestPasswordReset is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockPasswordResetServiceInterface_Expecter) RequestPasswordReset(ctx interface{}, email interface{}) *MockPasswordResetServiceInterface_RequestPasswordReset_Call {
	return &MockPasswordResetServiceInterface_RequestPasswordReset_Call{Call: _e.mock.On("RequestPasswordReset", ctx, email)}
}

func (_c *MockPasswordResetServiceInterface_RequestPasswordReset_Call) Run(run func(ctx context.Context, email string)) *MockPasswordResetServiceInterface_RequestPasswordReset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPasswordResetServiceInterface_RequestPasswordReset_Call) Return(_a0 error) *MockPasswordResetServiceInterface_RequestPasswordReset_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPasswordResetServiceInterface_RequestPasswordReset_Call) RunAndReturn(run func(context.Context, string) error) *MockPasswordResetServiceInterface_RequestPasswordReset_Call {
	_c.Call.Return(run)
	return _c
}

// ResetPassword provides a mock function with given fields: ctx, token, newPassword
func (_m *MockPasswordResetServiceInterface) ResetPassword(ctx context.Context, token string, newPassword string) error {
	ret := _m.Called(ctx, token, newPassword)

	if len(ret) == 0 {
		panic("no return value specified for ResetPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, token, newPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPasswordResetServiceInterface_ResetPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetPassword'
type MockPasswordResetServiceInterface_ResetPassword_Call struct {
	*mock.Call
}

// ResetPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - newPassword string
func (_e *MockPasswordResetServiceInterface_Expecter) ResetPassword(ctx interface{}, token interface{}, newPassword interface{}) *MockPasswordResetServiceInterface_ResetPassword_Call {
	return &MockPasswordResetServiceInterface_ResetPassword_Call{Call: _e.mock.On("ResetPassword", ctx, token, newPassword)}
}

func (_c *MockPasswordResetServiceInterface_ResetPassword_Call) Run(run func(ctx context.Context, token string, newPassword string)) *MockPasswordResetServiceInterface_ResetPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockPasswordResetServiceInterface_ResetPassword_Call) Return(_a0 error) *MockPasswordResetServiceInterface_ResetPassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPasswordResetServiceInterface_ResetPassword_Call) RunAndReturn(run func(context.Context, string, string) error) *MockPasswordResetServiceInterface_ResetPassword_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPasswordResetServiceInterface creates a new instance of MockPasswordResetServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPasswordResetServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPasswordResetServiceInterface {
	mock := &MockPasswordResetServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
