// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	models "myanimeapi/api/models"

	mock "github.com/stretchr/testify/mock"
)

// MockAuthServiceInterface is an autogenerated mock type for the AuthServiceInterface type
type MockAuthServiceInterface struct {
	mock.Mock
}

type MockAuthServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthServiceInterface) EXPECT() *MockAuthServiceInterface_Expecter {
	return &MockAuthServiceInterface_Expecter{mock: &_m.Mock}
}

// AuthenticateUser provides a mock function with given fields: ctx, credentials
func (_m *MockAuthServiceInterface) AuthenticateUser(ctx context.Context, credentials *models.UserCredentials) (string, error) {
	ret := _m.Called(ctx, credentials)

	if len(ret) == 0 {
		panic("no return value specified for AuthenticateUser")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.UserCredentials) (string, error)); ok {
		return rf(ctx, credentials)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.UserCredentials) string); ok {
		r0 = rf(ctx, credentials)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.UserCredentials) error); ok {
		r1 = rf(ctx, credentials)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthServiceInterface_AuthenticateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthenticateUser'
type MockAuthServiceInterface_AuthenticateUser_Call struct {
	*mock.Call
}

// AuthenticateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - credentials *models.UserCredentials
func (_e *MockAuthServiceInterface_Expecter) AuthenticateUser(ctx interface{}, credentials interface{}) *MockAuthServiceInterface_AuthenticateUser_Call {
	return &MockAuthServiceInterface_AuthenticateUser_Call{Call: _e.mock.On("AuthenticateUser", ctx, credentials)}
}

func (_c *MockAuthServiceInterface_AuthenticateUser_Call) Run(run func(ctx context.Context, credentials *models.UserCredentials)) *MockAuthServiceInterface_AuthenticateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.UserCredentials))
	})
	return _c
}

func (_c *MockAuthServiceInterface_AuthenticateUser_Call) Return(_a0 string, _a1 error) *MockAuthServiceInterface_AuthenticateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthServiceInterface_AuthenticateUser_Call) RunAndReturn(run func(context.Context, *models.UserCredentials) (string, error)) *MockAuthServiceInterface_AuthenticateUser_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterUser provides a mock function with given fields: ctx, user
func (_m *MockAuthServiceInterface) RegisterUser(ctx context.Context, user *models.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthServiceInterface_RegisterUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterUser'
type MockAuthServiceInterface_RegisterUser_Call struct {
	*mock.Call
}

// RegisterUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *models.User
func (_e *MockAuthServiceInterface_Expecter) RegisterUser(ctx interface{}, user interface{}) *MockAuthServiceInterface_RegisterUser_Call {
	return &MockAuthServiceInterface_RegisterUser_Call{Call: _e.mock.On("RegisterUser", ctx, user)}
}

func (_c *MockAuthServiceInterface_RegisterUser_Call) Run(run func(ctx context.Context, user *models.User)) *MockAuthServiceInterface_RegisterUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.User))
	})
	return _c
}

func (_c *MockAuthServiceInterface_RegisterUser_Call) Return(_a0 error) *MockAuthServiceInterface_RegisterUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthServiceInterface_RegisterUser_Call) RunAndReturn(run func(context.Context, *models.User) error) *MockAuthServiceInterface_RegisterUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthServiceInterface creates a new instance of MockAuthServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthServiceInterface {
	mock := &MockAuthServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
