// Code generated by MockGen. DO NOT EDIT.
// Source: api/repositories/repository.go

package mocks

import (
	"context"
	"reflect"

	"github.com/golang/mock/gomock"
	"myanimeapi/api/models"
)

// MockAnimeRepository is a mock of AnimeRepository interface.
type MockAnimeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAnimeRepositoryMockRecorder
}

// MockAnimeRepositoryMockRecorder is the mock recorder for MockAnimeRepository.
type MockAnimeRepositoryMockRecorder struct {
	mock *MockAnimeRepository
}

// NewMockAnimeRepository creates a new mock instance.
func NewMockAnimeRepository(ctrl *gomock.Controller) *MockAnimeRepository {
	mock := &MockAnimeRepository{ctrl: ctrl}
	mock.recorder = &MockAnimeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnimeRepository) EXPECT() *MockAnimeRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockAnimeRepository) GetByID(ctx context.Context, id uint) (*models.Anime, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Anime)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAnimeRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAnimeRepository)(nil).GetByID), ctx, id)
}

// GetAll mocks base method.
func (m *MockAnimeRepository) GetAll(ctx context.Context, page, pageSize int) ([]models.Anime, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, page, pageSize)
	ret0, _ := ret[0].([]models.Anime)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAll indicates an expected call of GetAll.
func (mr *MockAnimeRepositoryMockRecorder) GetAll(ctx, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockAnimeRepository)(nil).GetAll), ctx, page, pageSize)
}

// Create mocks base method.
func (m *MockAnimeRepository) Create(ctx context.Context, anime *models.Anime) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, anime)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAnimeRepositoryMockRecorder) Create(ctx, anime interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAnimeRepository)(nil).Create), ctx, anime)
}

// Update mocks base method.
func (m *MockAnimeRepository) Update(ctx context.Context, anime *models.Anime) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, anime)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAnimeRepositoryMockRecorder) Update(ctx, anime interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAnimeRepository)(nil).Update), ctx, anime)
}

// Delete mocks base method.
func (m *MockAnimeRepository) Delete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAnimeRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAnimeRepository)(nil).Delete), ctx, id)
}

// GetByTitle mocks base method.
func (m *MockAnimeRepository) GetByTitle(ctx context.Context, title string) (*models.Anime, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTitle", ctx, title)
	ret0, _ := ret[0].(*models.Anime)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTitle indicates an expected call of GetByTitle.
func (mr *MockAnimeRepositoryMockRecorder) GetByTitle(ctx, title interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTitle", reflect.TypeOf((*MockAnimeRepository)(nil).GetByTitle), ctx, title)
}

// GetByGenre mocks base method.
func (m *MockAnimeRepository) GetByGenre(ctx context.Context, genre string, page, pageSize int) ([]models.Anime, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByGenre", ctx, genre, page, pageSize)
	ret0, _ := ret[0].([]models.Anime)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByGenre indicates an expected call of GetByGenre.
func (mr *MockAnimeRepositoryMockRecorder) GetByGenre(ctx, genre, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByGenre", reflect.TypeOf((*MockAnimeRepository)(nil).GetByGenre), ctx, genre, page, pageSize)
}

// GetReviewsForAnime mocks base method.
func (m *MockAnimeRepository) GetReviewsForAnime(ctx context.Context, animeID uint, page, pageSize int) ([]models.Review, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReviewsForAnime", ctx, animeID, page, pageSize)
	ret0, _ := ret[0].([]models.Review)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetReviewsForAnime indicates an expected call of GetReviewsForAnime.
func (mr *MockAnimeRepositoryMockRecorder) GetReviewsForAnime(ctx, animeID, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReviewsForAnime", reflect.TypeOf((*MockAnimeRepository)(nil).GetReviewsForAnime), ctx, animeID, page, pageSize)
} 