// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	models "myanimeapi/api/models"

	mock "github.com/stretchr/testify/mock"
)

// MockReviewServiceInterface is an autogenerated mock type for the ReviewServiceInterface type
type MockReviewServiceInterface struct {
	mock.Mock
}

type MockReviewServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReviewServiceInterface) EXPECT() *MockReviewServiceInterface_Expecter {
	return &MockReviewServiceInterface_Expecter{mock: &_m.Mock}
}

// CreateReview provides a mock function with given fields: ctx, review
func (_m *MockReviewServiceInterface) CreateReview(ctx context.Context, review *models.Review) error {
	ret := _m.Called(ctx, review)

	if len(ret) == 0 {
		panic("no return value specified for CreateReview")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Review) error); ok {
		r0 = rf(ctx, review)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReviewServiceInterface_CreateReview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateReview'
type MockReviewServiceInterface_CreateReview_Call struct {
	*mock.Call
}

// CreateReview is a helper method to define mock.On call
//   - ctx context.Context
//   - review *models.Review
func (_e *MockReviewServiceInterface_Expecter) CreateReview(ctx interface{}, review interface{}) *MockReviewServiceInterface_CreateReview_Call {
	return &MockReviewServiceInterface_CreateReview_Call{Call: _e.mock.On("CreateReview", ctx, review)}
}

func (_c *MockReviewServiceInterface_CreateReview_Call) Run(run func(ctx context.Context, review *models.Review)) *MockReviewServiceInterface_CreateReview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Review))
	})
	return _c
}

func (_c *MockReviewServiceInterface_CreateReview_Call) Return(_a0 error) *MockReviewServiceInterface_CreateReview_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReviewServiceInterface_CreateReview_Call) RunAndReturn(run func(context.Context, *models.Review) error) *MockReviewServiceInterface_CreateReview_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteReview provides a mock function with given fields: ctx, id
func (_m *MockReviewServiceInterface) DeleteReview(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteReview")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReviewServiceInterface_DeleteReview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteReview'
type MockReviewServiceInterface_DeleteReview_Call struct {
	*mock.Call
}

// DeleteReview is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockReviewServiceInterface_Expecter) DeleteReview(ctx interface{}, id interface{}) *MockReviewServiceInterface_DeleteReview_Call {
	return &MockReviewServiceInterface_DeleteReview_Call{Call: _e.mock.On("DeleteReview", ctx, id)}
}

func (_c *MockReviewServiceInterface_DeleteReview_Call) Run(run func(ctx context.Context, id uint)) *MockReviewServiceInterface_DeleteReview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockReviewServiceInterface_DeleteReview_Call) Return(_a0 error) *MockReviewServiceInterface_DeleteReview_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReviewServiceInterface_DeleteReview_Call) RunAndReturn(run func(context.Context, uint) error) *MockReviewServiceInterface_DeleteReview_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllReviews provides a mock function with given fields: ctx, page, limit
func (_m *MockReviewServiceInterface) GetAllReviews(ctx context.Context, page int, limit int) ([]models.Review, int64, error) {
	ret := _m.Called(ctx, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetAllReviews")
	}

	var r0 []models.Review
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]models.Review, int64, error)); ok {
		return rf(ctx, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []models.Review); ok {
		r0 = rf(ctx, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Review)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int64); ok {
		r1 = rf(ctx, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockReviewServiceInterface_GetAllReviews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllReviews'
type MockReviewServiceInterface_GetAllReviews_Call struct {
	*mock.Call
}

// GetAllReviews is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - limit int
func (_e *MockReviewServiceInterface_Expecter) GetAllReviews(ctx interface{}, page interface{}, limit interface{}) *MockReviewServiceInterface_GetAllReviews_Call {
	return &MockReviewServiceInterface_GetAllReviews_Call{Call: _e.mock.On("GetAllReviews", ctx, page, limit)}
}

func (_c *MockReviewServiceInterface_GetAllReviews_Call) Run(run func(ctx context.Context, page int, limit int)) *MockReviewServiceInterface_GetAllReviews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockReviewServiceInterface_GetAllReviews_Call) Return(_a0 []models.Review, _a1 int64, _a2 error) *MockReviewServiceInterface_GetAllReviews_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockReviewServiceInterface_GetAllReviews_Call) RunAndReturn(run func(context.Context, int, int) ([]models.Review, int64, error)) *MockReviewServiceInterface_GetAllReviews_Call {
	_c.Call.Return(run)
	return _c
}

// GetReviewByID provides a mock function with given fields: ctx, id
func (_m *MockReviewServiceInterface) GetReviewByID(ctx context.Context, id uint) (*models.Review, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetReviewByID")
	}

	var r0 *models.Review
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*models.Review, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *models.Review); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Review)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReviewServiceInterface_GetReviewByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReviewByID'
type MockReviewServiceInterface_GetReviewByID_Call struct {
	*mock.Call
}

// GetReviewByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockReviewServiceInterface_Expecter) GetReviewByID(ctx interface{}, id interface{}) *MockReviewServiceInterface_GetReviewByID_Call {
	return &MockReviewServiceInterface_GetReviewByID_Call{Call: _e.mock.On("GetReviewByID", ctx, id)}
}

func (_c *MockReviewServiceInterface_GetReviewByID_Call) Run(run func(ctx context.Context, id uint)) *MockReviewServiceInterface_GetReviewByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockReviewServiceInterface_GetReviewByID_Call) Return(_a0 *models.Review, _a1 error) *MockReviewServiceInterface_GetReviewByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReviewServiceInterface_GetReviewByID_Call) RunAndReturn(run func(context.Context, uint) (*models.Review, error)) *MockReviewServiceInterface_GetReviewByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetReviewsByAnimeID provides a mock function with given fields: ctx, animeID, page, limit
func (_m *MockReviewServiceInterface) GetReviewsByAnimeID(ctx context.Context, animeID uint, page int, limit int) ([]models.Review, int64, error) {
	ret := _m.Called(ctx, animeID, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetReviewsByAnimeID")
	}

	var r0 []models.Review
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, int, int) ([]models.Review, int64, error)); ok {
		return rf(ctx, animeID, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, int, int) []models.Review); ok {
		r0 = rf(ctx, animeID, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Review)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, int, int) int64); ok {
		r1 = rf(ctx, animeID, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uint, int, int) error); ok {
		r2 = rf(ctx, animeID, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockReviewServiceInterface_GetReviewsByAnimeID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReviewsByAnimeID'
type MockReviewServiceInterface_GetReviewsByAnimeID_Call struct {
	*mock.Call
}

// GetReviewsByAnimeID is a helper method to define mock.On call
//   - ctx context.Context
//   - animeID uint
//   - page int
//   - limit int
func (_e *MockReviewServiceInterface_Expecter) GetReviewsByAnimeID(ctx interface{}, animeID interface{}, page interface{}, limit interface{}) *MockReviewServiceInterface_GetReviewsByAnimeID_Call {
	return &MockReviewServiceInterface_GetReviewsByAnimeID_Call{Call: _e.mock.On("GetReviewsByAnimeID", ctx, animeID, page, limit)}
}

func (_c *MockReviewServiceInterface_GetReviewsByAnimeID_Call) Run(run func(ctx context.Context, animeID uint, page int, limit int)) *MockReviewServiceInterface_GetReviewsByAnimeID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockReviewServiceInterface_GetReviewsByAnimeID_Call) Return(_a0 []models.Review, _a1 int64, _a2 error) *MockReviewServiceInterface_GetReviewsByAnimeID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockReviewServiceInterface_GetReviewsByAnimeID_Call) RunAndReturn(run func(context.Context, uint, int, int) ([]models.Review, int64, error)) *MockReviewServiceInterface_GetReviewsByAnimeID_Call {
	_c.Call.Return(run)
	return _c
}

// GetReviewsByUserID provides a mock function with given fields: ctx, userID, page, limit
func (_m *MockReviewServiceInterface) GetReviewsByUserID(ctx context.Context, userID uint, page int, limit int) ([]models.Review, int64, error) {
	ret := _m.Called(ctx, userID, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetReviewsByUserID")
	}

	var r0 []models.Review
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, int, int) ([]models.Review, int64, error)); ok {
		return rf(ctx, userID, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, int, int) []models.Review); ok {
		r0 = rf(ctx, userID, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Review)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, int, int) int64); ok {
		r1 = rf(ctx, userID, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uint, int, int) error); ok {
		r2 = rf(ctx, userID, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockReviewServiceInterface_GetReviewsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReviewsByUserID'
type MockReviewServiceInterface_GetReviewsByUserID_Call struct {
	*mock.Call
}

// GetReviewsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - page int
//   - limit int
func (_e *MockReviewServiceInterface_Expecter) GetReviewsByUserID(ctx interface{}, userID interface{}, page interface{}, limit interface{}) *MockReviewServiceInterface_GetReviewsByUserID_Call {
	return &MockReviewServiceInterface_GetReviewsByUserID_Call{Call: _e.mock.On("GetReviewsByUserID", ctx, userID, page, limit)}
}

func (_c *MockReviewServiceInterface_GetReviewsByUserID_Call) Run(run func(ctx context.Context, userID uint, page int, limit int)) *MockReviewServiceInterface_GetReviewsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockReviewServiceInterface_GetReviewsByUserID_Call) Return(_a0 []models.Review, _a1 int64, _a2 error) *MockReviewServiceInterface_GetReviewsByUserID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockReviewServiceInterface_GetReviewsByUserID_Call) RunAndReturn(run func(context.Context, uint, int, int) ([]models.Review, int64, error)) *MockReviewServiceInterface_GetReviewsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateReview provides a mock function with given fields: ctx, review
func (_m *MockReviewServiceInterface) UpdateReview(ctx context.Context, review *models.Review) error {
	ret := _m.Called(ctx, review)

	if len(ret) == 0 {
		panic("no return value specified for UpdateReview")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Review) error); ok {
		r0 = rf(ctx, review)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReviewServiceInterface_UpdateReview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateReview'
type MockReviewServiceInterface_UpdateReview_Call struct {
	*mock.Call
}

// UpdateReview is a helper method to define mock.On call
//   - ctx context.Context
//   - review *models.Review
func (_e *MockReviewServiceInterface_Expecter) UpdateReview(ctx interface{}, review interface{}) *MockReviewServiceInterface_UpdateReview_Call {
	return &MockReviewServiceInterface_UpdateReview_Call{Call: _e.mock.On("UpdateReview", ctx, review)}
}

func (_c *MockReviewServiceInterface_UpdateReview_Call) Run(run func(ctx context.Context, review *models.Review)) *MockReviewServiceInterface_UpdateReview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Review))
	})
	return _c
}

func (_c *MockReviewServiceInterface_UpdateReview_Call) Return(_a0 error) *MockReviewServiceInterface_UpdateReview_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReviewServiceInterface_UpdateReview_Call) RunAndReturn(run func(context.Context, *models.Review) error) *MockReviewServiceInterface_UpdateReview_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReviewServiceInterface creates a new instance of MockReviewServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReviewServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReviewServiceInterface {
	mock := &MockReviewServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
