// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	models "myanimeapi/api/models"

	mock "github.com/stretchr/testify/mock"
)

// MockTagServiceInterface is an autogenerated mock type for the TagServiceInterface type
type MockTagServiceInterface struct {
	mock.Mock
}

type MockTagServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTagServiceInterface) EXPECT() *MockTagServiceInterface_Expecter {
	return &MockTagServiceInterface_Expecter{mock: &_m.Mock}
}

// CreateTag provides a mock function with given fields: ctx, tag
func (_m *MockTagServiceInterface) CreateTag(ctx context.Context, tag *models.Tag) error {
	ret := _m.Called(ctx, tag)

	if len(ret) == 0 {
		panic("no return value specified for CreateTag")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Tag) error); ok {
		r0 = rf(ctx, tag)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTagServiceInterface_CreateTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTag'
type MockTagServiceInterface_CreateTag_Call struct {
	*mock.Call
}

// CreateTag is a helper method to define mock.On call
//   - ctx context.Context
//   - tag *models.Tag
func (_e *MockTagServiceInterface_Expecter) CreateTag(ctx interface{}, tag interface{}) *MockTagServiceInterface_CreateTag_Call {
	return &MockTagServiceInterface_CreateTag_Call{Call: _e.mock.On("CreateTag", ctx, tag)}
}

func (_c *MockTagServiceInterface_CreateTag_Call) Run(run func(ctx context.Context, tag *models.Tag)) *MockTagServiceInterface_CreateTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Tag))
	})
	return _c
}

func (_c *MockTagServiceInterface_CreateTag_Call) Return(_a0 error) *MockTagServiceInterface_CreateTag_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTagServiceInterface_CreateTag_Call) RunAndReturn(run func(context.Context, *models.Tag) error) *MockTagServiceInterface_CreateTag_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTag provides a mock function with given fields: ctx, id
func (_m *MockTagServiceInterface) DeleteTag(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTag")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTagServiceInterface_DeleteTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTag'
type MockTagServiceInterface_DeleteTag_Call struct {
	*mock.Call
}

// DeleteTag is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockTagServiceInterface_Expecter) DeleteTag(ctx interface{}, id interface{}) *MockTagServiceInterface_DeleteTag_Call {
	return &MockTagServiceInterface_DeleteTag_Call{Call: _e.mock.On("DeleteTag", ctx, id)}
}

func (_c *MockTagServiceInterface_DeleteTag_Call) Run(run func(ctx context.Context, id uint)) *MockTagServiceInterface_DeleteTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockTagServiceInterface_DeleteTag_Call) Return(_a0 error) *MockTagServiceInterface_DeleteTag_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTagServiceInterface_DeleteTag_Call) RunAndReturn(run func(context.Context, uint) error) *MockTagServiceInterface_DeleteTag_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllTags provides a mock function with given fields: ctx, page, limit
func (_m *MockTagServiceInterface) GetAllTags(ctx context.Context, page int, limit int) ([]models.Tag, int64, error) {
	ret := _m.Called(ctx, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetAllTags")
	}

	var r0 []models.Tag
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]models.Tag, int64, error)); ok {
		return rf(ctx, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []models.Tag); ok {
		r0 = rf(ctx, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Tag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int64); ok {
		r1 = rf(ctx, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTagServiceInterface_GetAllTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllTags'
type MockTagServiceInterface_GetAllTags_Call struct {
	*mock.Call
}

// GetAllTags is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - limit int
func (_e *MockTagServiceInterface_Expecter) GetAllTags(ctx interface{}, page interface{}, limit interface{}) *MockTagServiceInterface_GetAllTags_Call {
	return &MockTagServiceInterface_GetAllTags_Call{Call: _e.mock.On("GetAllTags", ctx, page, limit)}
}

func (_c *MockTagServiceInterface_GetAllTags_Call) Run(run func(ctx context.Context, page int, limit int)) *MockTagServiceInterface_GetAllTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockTagServiceInterface_GetAllTags_Call) Return(_a0 []models.Tag, _a1 int64, _a2 error) *MockTagServiceInterface_GetAllTags_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockTagServiceInterface_GetAllTags_Call) RunAndReturn(run func(context.Context, int, int) ([]models.Tag, int64, error)) *MockTagServiceInterface_GetAllTags_Call {
	_c.Call.Return(run)
	return _c
}

// GetTagByID provides a mock function with given fields: ctx, id
func (_m *MockTagServiceInterface) GetTagByID(ctx context.Context, id uint) (*models.Tag, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTagByID")
	}

	var r0 *models.Tag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*models.Tag, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *models.Tag); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Tag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTagServiceInterface_GetTagByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTagByID'
type MockTagServiceInterface_GetTagByID_Call struct {
	*mock.Call
}

// GetTagByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockTagServiceInterface_Expecter) GetTagByID(ctx interface{}, id interface{}) *MockTagServiceInterface_GetTagByID_Call {
	return &MockTagServiceInterface_GetTagByID_Call{Call: _e.mock.On("GetTagByID", ctx, id)}
}

func (_c *MockTagServiceInterface_GetTagByID_Call) Run(run func(ctx context.Context, id uint)) *MockTagServiceInterface_GetTagByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockTagServiceInterface_GetTagByID_Call) Return(_a0 *models.Tag, _a1 error) *MockTagServiceInterface_GetTagByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTagServiceInterface_GetTagByID_Call) RunAndReturn(run func(context.Context, uint) (*models.Tag, error)) *MockTagServiceInterface_GetTagByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTagsByIDs provides a mock function with given fields: ctx, ids
func (_m *MockTagServiceInterface) GetTagsByIDs(ctx context.Context, ids []uint) ([]models.Tag, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetTagsByIDs")
	}

	var r0 []models.Tag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint) ([]models.Tag, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uint) []models.Tag); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Tag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uint) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTagServiceInterface_GetTagsByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTagsByIDs'
type MockTagServiceInterface_GetTagsByIDs_Call struct {
	*mock.Call
}

// GetTagsByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uint
func (_e *MockTagServiceInterface_Expecter) GetTagsByIDs(ctx interface{}, ids interface{}) *MockTagServiceInterface_GetTagsByIDs_Call {
	return &MockTagServiceInterface_GetTagsByIDs_Call{Call: _e.mock.On("GetTagsByIDs", ctx, ids)}
}

func (_c *MockTagServiceInterface_GetTagsByIDs_Call) Run(run func(ctx context.Context, ids []uint)) *MockTagServiceInterface_GetTagsByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uint))
	})
	return _c
}

func (_c *MockTagServiceInterface_GetTagsByIDs_Call) Return(_a0 []models.Tag, _a1 error) *MockTagServiceInterface_GetTagsByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTagServiceInterface_GetTagsByIDs_Call) RunAndReturn(run func(context.Context, []uint) ([]models.Tag, error)) *MockTagServiceInterface_GetTagsByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTag provides a mock function with given fields: ctx, tag
func (_m *MockTagServiceInterface) UpdateTag(ctx context.Context, tag *models.Tag) error {
	ret := _m.Called(ctx, tag)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTag")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Tag) error); ok {
		r0 = rf(ctx, tag)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTagServiceInterface_UpdateTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTag'
type MockTagServiceInterface_UpdateTag_Call struct {
	*mock.Call
}

// UpdateTag is a helper method to define mock.On call
//   - ctx context.Context
//   - tag *models.Tag
func (_e *MockTagServiceInterface_Expecter) UpdateTag(ctx interface{}, tag interface{}) *MockTagServiceInterface_UpdateTag_Call {
	return &MockTagServiceInterface_UpdateTag_Call{Call: _e.mock.On("UpdateTag", ctx, tag)}
}

func (_c *MockTagServiceInterface_UpdateTag_Call) Run(run func(ctx context.Context, tag *models.Tag)) *MockTagServiceInterface_UpdateTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Tag))
	})
	return _c
}

func (_c *MockTagServiceInterface_UpdateTag_Call) Return(_a0 error) *MockTagServiceInterface_UpdateTag_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTagServiceInterface_UpdateTag_Call) RunAndReturn(run func(context.Context, *models.Tag) error) *MockTagServiceInterface_UpdateTag_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTagServiceInterface creates a new instance of MockTagServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTagServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTagServiceInterface {
	mock := &MockTagServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
