// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	multipart "mime/multipart"

	mock "github.com/stretchr/testify/mock"
)

// MockStorageServiceInterface is an autogenerated mock type for the StorageServiceInterface type
type MockStorageServiceInterface struct {
	mock.Mock
}

type MockStorageServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorageServiceInterface) EXPECT() *MockStorageServiceInterface_Expecter {
	return &MockStorageServiceInterface_Expecter{mock: &_m.Mock}
}

// DeleteFile provides a mock function with given fields: ctx, fileURL
func (_m *MockStorageServiceInterface) DeleteFile(ctx context.Context, fileURL string) error {
	ret := _m.Called(ctx, fileURL)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, fileURL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorageServiceInterface_DeleteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFile'
type MockStorageServiceInterface_DeleteFile_Call struct {
	*mock.Call
}

// DeleteFile is a helper method to define mock.On call
//   - ctx context.Context
//   - fileURL string
func (_e *MockStorageServiceInterface_Expecter) DeleteFile(ctx interface{}, fileURL interface{}) *MockStorageServiceInterface_DeleteFile_Call {
	return &MockStorageServiceInterface_DeleteFile_Call{Call: _e.mock.On("DeleteFile", ctx, fileURL)}
}

func (_c *MockStorageServiceInterface_DeleteFile_Call) Run(run func(ctx context.Context, fileURL string)) *MockStorageServiceInterface_DeleteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorageServiceInterface_DeleteFile_Call) Return(_a0 error) *MockStorageServiceInterface_DeleteFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorageServiceInterface_DeleteFile_Call) RunAndReturn(run func(context.Context, string) error) *MockStorageServiceInterface_DeleteFile_Call {
	_c.Call.Return(run)
	return _c
}

// GetBaseURL provides a mock function with no fields
func (_m *MockStorageServiceInterface) GetBaseURL() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBaseURL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockStorageServiceInterface_GetBaseURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBaseURL'
type MockStorageServiceInterface_GetBaseURL_Call struct {
	*mock.Call
}

// GetBaseURL is a helper method to define mock.On call
func (_e *MockStorageServiceInterface_Expecter) GetBaseURL() *MockStorageServiceInterface_GetBaseURL_Call {
	return &MockStorageServiceInterface_GetBaseURL_Call{Call: _e.mock.On("GetBaseURL")}
}

func (_c *MockStorageServiceInterface_GetBaseURL_Call) Run(run func()) *MockStorageServiceInterface_GetBaseURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorageServiceInterface_GetBaseURL_Call) Return(_a0 string) *MockStorageServiceInterface_GetBaseURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorageServiceInterface_GetBaseURL_Call) RunAndReturn(run func() string) *MockStorageServiceInterface_GetBaseURL_Call {
	_c.Call.Return(run)
	return _c
}

// SaveFile provides a mock function with given fields: file, directory
func (_m *MockStorageServiceInterface) SaveFile(file *multipart.FileHeader, directory string) (string, error) {
	ret := _m.Called(file, directory)

	if len(ret) == 0 {
		panic("no return value specified for SaveFile")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*multipart.FileHeader, string) (string, error)); ok {
		return rf(file, directory)
	}
	if rf, ok := ret.Get(0).(func(*multipart.FileHeader, string) string); ok {
		r0 = rf(file, directory)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*multipart.FileHeader, string) error); ok {
		r1 = rf(file, directory)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorageServiceInterface_SaveFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveFile'
type MockStorageServiceInterface_SaveFile_Call struct {
	*mock.Call
}

// SaveFile is a helper method to define mock.On call
//   - file *multipart.FileHeader
//   - directory string
func (_e *MockStorageServiceInterface_Expecter) SaveFile(file interface{}, directory interface{}) *MockStorageServiceInterface_SaveFile_Call {
	return &MockStorageServiceInterface_SaveFile_Call{Call: _e.mock.On("SaveFile", file, directory)}
}

func (_c *MockStorageServiceInterface_SaveFile_Call) Run(run func(file *multipart.FileHeader, directory string)) *MockStorageServiceInterface_SaveFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*multipart.FileHeader), args[1].(string))
	})
	return _c
}

func (_c *MockStorageServiceInterface_SaveFile_Call) Return(_a0 string, _a1 error) *MockStorageServiceInterface_SaveFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorageServiceInterface_SaveFile_Call) RunAndReturn(run func(*multipart.FileHeader, string) (string, error)) *MockStorageServiceInterface_SaveFile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorageServiceInterface creates a new instance of MockStorageServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorageServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorageServiceInterface {
	mock := &MockStorageServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
