// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	models "myanimeapi/api/models"

	mock "github.com/stretchr/testify/mock"
)

// MockGenreServiceInterface is an autogenerated mock type for the GenreServiceInterface type
type MockGenreServiceInterface struct {
	mock.Mock
}

type MockGenreServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenreServiceInterface) EXPECT() *MockGenreServiceInterface_Expecter {
	return &MockGenreServiceInterface_Expecter{mock: &_m.Mock}
}

// BulkCreateGenres provides a mock function with given fields: ctx, genres
func (_m *MockGenreServiceInterface) BulkCreateGenres(ctx context.Context, genres []models.Genre) error {
	ret := _m.Called(ctx, genres)

	if len(ret) == 0 {
		panic("no return value specified for BulkCreateGenres")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []models.Genre) error); ok {
		r0 = rf(ctx, genres)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGenreServiceInterface_BulkCreateGenres_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkCreateGenres'
type MockGenreServiceInterface_BulkCreateGenres_Call struct {
	*mock.Call
}

// BulkCreateGenres is a helper method to define mock.On call
//   - ctx context.Context
//   - genres []models.Genre
func (_e *MockGenreServiceInterface_Expecter) BulkCreateGenres(ctx interface{}, genres interface{}) *MockGenreServiceInterface_BulkCreateGenres_Call {
	return &MockGenreServiceInterface_BulkCreateGenres_Call{Call: _e.mock.On("BulkCreateGenres", ctx, genres)}
}

func (_c *MockGenreServiceInterface_BulkCreateGenres_Call) Run(run func(ctx context.Context, genres []models.Genre)) *MockGenreServiceInterface_BulkCreateGenres_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]models.Genre))
	})
	return _c
}

func (_c *MockGenreServiceInterface_BulkCreateGenres_Call) Return(_a0 error) *MockGenreServiceInterface_BulkCreateGenres_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGenreServiceInterface_BulkCreateGenres_Call) RunAndReturn(run func(context.Context, []models.Genre) error) *MockGenreServiceInterface_BulkCreateGenres_Call {
	_c.Call.Return(run)
	return _c
}

// BulkDeleteGenres provides a mock function with given fields: ctx, ids
func (_m *MockGenreServiceInterface) BulkDeleteGenres(ctx context.Context, ids []uint) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for BulkDeleteGenres")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGenreServiceInterface_BulkDeleteGenres_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkDeleteGenres'
type MockGenreServiceInterface_BulkDeleteGenres_Call struct {
	*mock.Call
}

// BulkDeleteGenres is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uint
func (_e *MockGenreServiceInterface_Expecter) BulkDeleteGenres(ctx interface{}, ids interface{}) *MockGenreServiceInterface_BulkDeleteGenres_Call {
	return &MockGenreServiceInterface_BulkDeleteGenres_Call{Call: _e.mock.On("BulkDeleteGenres", ctx, ids)}
}

func (_c *MockGenreServiceInterface_BulkDeleteGenres_Call) Run(run func(ctx context.Context, ids []uint)) *MockGenreServiceInterface_BulkDeleteGenres_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uint))
	})
	return _c
}

func (_c *MockGenreServiceInterface_BulkDeleteGenres_Call) Return(_a0 error) *MockGenreServiceInterface_BulkDeleteGenres_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGenreServiceInterface_BulkDeleteGenres_Call) RunAndReturn(run func(context.Context, []uint) error) *MockGenreServiceInterface_BulkDeleteGenres_Call {
	_c.Call.Return(run)
	return _c
}

// CreateGenre provides a mock function with given fields: ctx, genre
func (_m *MockGenreServiceInterface) CreateGenre(ctx context.Context, genre *models.Genre) error {
	ret := _m.Called(ctx, genre)

	if len(ret) == 0 {
		panic("no return value specified for CreateGenre")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Genre) error); ok {
		r0 = rf(ctx, genre)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGenreServiceInterface_CreateGenre_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGenre'
type MockGenreServiceInterface_CreateGenre_Call struct {
	*mock.Call
}

// CreateGenre is a helper method to define mock.On call
//   - ctx context.Context
//   - genre *models.Genre
func (_e *MockGenreServiceInterface_Expecter) CreateGenre(ctx interface{}, genre interface{}) *MockGenreServiceInterface_CreateGenre_Call {
	return &MockGenreServiceInterface_CreateGenre_Call{Call: _e.mock.On("CreateGenre", ctx, genre)}
}

func (_c *MockGenreServiceInterface_CreateGenre_Call) Run(run func(ctx context.Context, genre *models.Genre)) *MockGenreServiceInterface_CreateGenre_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Genre))
	})
	return _c
}

func (_c *MockGenreServiceInterface_CreateGenre_Call) Return(_a0 error) *MockGenreServiceInterface_CreateGenre_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGenreServiceInterface_CreateGenre_Call) RunAndReturn(run func(context.Context, *models.Genre) error) *MockGenreServiceInterface_CreateGenre_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteGenre provides a mock function with given fields: ctx, id
func (_m *MockGenreServiceInterface) DeleteGenre(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteGenre")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGenreServiceInterface_DeleteGenre_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteGenre'
type MockGenreServiceInterface_DeleteGenre_Call struct {
	*mock.Call
}

// DeleteGenre is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockGenreServiceInterface_Expecter) DeleteGenre(ctx interface{}, id interface{}) *MockGenreServiceInterface_DeleteGenre_Call {
	return &MockGenreServiceInterface_DeleteGenre_Call{Call: _e.mock.On("DeleteGenre", ctx, id)}
}

func (_c *MockGenreServiceInterface_DeleteGenre_Call) Run(run func(ctx context.Context, id uint)) *MockGenreServiceInterface_DeleteGenre_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockGenreServiceInterface_DeleteGenre_Call) Return(_a0 error) *MockGenreServiceInterface_DeleteGenre_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGenreServiceInterface_DeleteGenre_Call) RunAndReturn(run func(context.Context, uint) error) *MockGenreServiceInterface_DeleteGenre_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllGenres provides a mock function with given fields: ctx, page, limit
func (_m *MockGenreServiceInterface) GetAllGenres(ctx context.Context, page int, limit int) ([]models.Genre, int64, error) {
	ret := _m.Called(ctx, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetAllGenres")
	}

	var r0 []models.Genre
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]models.Genre, int64, error)); ok {
		return rf(ctx, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []models.Genre); ok {
		r0 = rf(ctx, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Genre)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int64); ok {
		r1 = rf(ctx, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockGenreServiceInterface_GetAllGenres_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllGenres'
type MockGenreServiceInterface_GetAllGenres_Call struct {
	*mock.Call
}

// GetAllGenres is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - limit int
func (_e *MockGenreServiceInterface_Expecter) GetAllGenres(ctx interface{}, page interface{}, limit interface{}) *MockGenreServiceInterface_GetAllGenres_Call {
	return &MockGenreServiceInterface_GetAllGenres_Call{Call: _e.mock.On("GetAllGenres", ctx, page, limit)}
}

func (_c *MockGenreServiceInterface_GetAllGenres_Call) Run(run func(ctx context.Context, page int, limit int)) *MockGenreServiceInterface_GetAllGenres_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockGenreServiceInterface_GetAllGenres_Call) Return(_a0 []models.Genre, _a1 int64, _a2 error) *MockGenreServiceInterface_GetAllGenres_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockGenreServiceInterface_GetAllGenres_Call) RunAndReturn(run func(context.Context, int, int) ([]models.Genre, int64, error)) *MockGenreServiceInterface_GetAllGenres_Call {
	_c.Call.Return(run)
	return _c
}

// GetGenreByID provides a mock function with given fields: ctx, id
func (_m *MockGenreServiceInterface) GetGenreByID(ctx context.Context, id uint) (*models.Genre, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetGenreByID")
	}

	var r0 *models.Genre
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*models.Genre, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *models.Genre); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Genre)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGenreServiceInterface_GetGenreByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGenreByID'
type MockGenreServiceInterface_GetGenreByID_Call struct {
	*mock.Call
}

// GetGenreByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockGenreServiceInterface_Expecter) GetGenreByID(ctx interface{}, id interface{}) *MockGenreServiceInterface_GetGenreByID_Call {
	return &MockGenreServiceInterface_GetGenreByID_Call{Call: _e.mock.On("GetGenreByID", ctx, id)}
}

func (_c *MockGenreServiceInterface_GetGenreByID_Call) Run(run func(ctx context.Context, id uint)) *MockGenreServiceInterface_GetGenreByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockGenreServiceInterface_GetGenreByID_Call) Return(_a0 *models.Genre, _a1 error) *MockGenreServiceInterface_GetGenreByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGenreServiceInterface_GetGenreByID_Call) RunAndReturn(run func(context.Context, uint) (*models.Genre, error)) *MockGenreServiceInterface_GetGenreByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetGenresByIDs provides a mock function with given fields: ctx, ids
func (_m *MockGenreServiceInterface) GetGenresByIDs(ctx context.Context, ids []uint) ([]models.Genre, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetGenresByIDs")
	}

	var r0 []models.Genre
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint) ([]models.Genre, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uint) []models.Genre); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Genre)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uint) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGenreServiceInterface_GetGenresByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGenresByIDs'
type MockGenreServiceInterface_GetGenresByIDs_Call struct {
	*mock.Call
}

// GetGenresByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uint
func (_e *MockGenreServiceInterface_Expecter) GetGenresByIDs(ctx interface{}, ids interface{}) *MockGenreServiceInterface_GetGenresByIDs_Call {
	return &MockGenreServiceInterface_GetGenresByIDs_Call{Call: _e.mock.On("GetGenresByIDs", ctx, ids)}
}

func (_c *MockGenreServiceInterface_GetGenresByIDs_Call) Run(run func(ctx context.Context, ids []uint)) *MockGenreServiceInterface_GetGenresByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uint))
	})
	return _c
}

func (_c *MockGenreServiceInterface_GetGenresByIDs_Call) Return(_a0 []models.Genre, _a1 error) *MockGenreServiceInterface_GetGenresByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGenreServiceInterface_GetGenresByIDs_Call) RunAndReturn(run func(context.Context, []uint) ([]models.Genre, error)) *MockGenreServiceInterface_GetGenresByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// SearchGenres provides a mock function with given fields: ctx, query, page, limit
func (_m *MockGenreServiceInterface) SearchGenres(ctx context.Context, query string, page int, limit int) ([]models.Genre, int64, error) {
	ret := _m.Called(ctx, query, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for SearchGenres")
	}

	var r0 []models.Genre
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]models.Genre, int64, error)); ok {
		return rf(ctx, query, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []models.Genre); ok {
		r0 = rf(ctx, query, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Genre)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int64); ok {
		r1 = rf(ctx, query, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, query, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockGenreServiceInterface_SearchGenres_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchGenres'
type MockGenreServiceInterface_SearchGenres_Call struct {
	*mock.Call
}

// SearchGenres is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - page int
//   - limit int
func (_e *MockGenreServiceInterface_Expecter) SearchGenres(ctx interface{}, query interface{}, page interface{}, limit interface{}) *MockGenreServiceInterface_SearchGenres_Call {
	return &MockGenreServiceInterface_SearchGenres_Call{Call: _e.mock.On("SearchGenres", ctx, query, page, limit)}
}

func (_c *MockGenreServiceInterface_SearchGenres_Call) Run(run func(ctx context.Context, query string, page int, limit int)) *MockGenreServiceInterface_SearchGenres_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockGenreServiceInterface_SearchGenres_Call) Return(_a0 []models.Genre, _a1 int64, _a2 error) *MockGenreServiceInterface_SearchGenres_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockGenreServiceInterface_SearchGenres_Call) RunAndReturn(run func(context.Context, string, int, int) ([]models.Genre, int64, error)) *MockGenreServiceInterface_SearchGenres_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateGenre provides a mock function with given fields: ctx, genre
func (_m *MockGenreServiceInterface) UpdateGenre(ctx context.Context, genre *models.Genre) error {
	ret := _m.Called(ctx, genre)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGenre")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Genre) error); ok {
		r0 = rf(ctx, genre)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGenreServiceInterface_UpdateGenre_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateGenre'
type MockGenreServiceInterface_UpdateGenre_Call struct {
	*mock.Call
}

// UpdateGenre is a helper method to define mock.On call
//   - ctx context.Context
//   - genre *models.Genre
func (_e *MockGenreServiceInterface_Expecter) UpdateGenre(ctx interface{}, genre interface{}) *MockGenreServiceInterface_UpdateGenre_Call {
	return &MockGenreServiceInterface_UpdateGenre_Call{Call: _e.mock.On("UpdateGenre", ctx, genre)}
}

func (_c *MockGenreServiceInterface_UpdateGenre_Call) Run(run func(ctx context.Context, genre *models.Genre)) *MockGenreServiceInterface_UpdateGenre_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Genre))
	})
	return _c
}

func (_c *MockGenreServiceInterface_UpdateGenre_Call) Return(_a0 error) *MockGenreServiceInterface_UpdateGenre_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGenreServiceInterface_UpdateGenre_Call) RunAndReturn(run func(context.Context, *models.Genre) error) *MockGenreServiceInterface_UpdateGenre_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGenreServiceInterface creates a new instance of MockGenreServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenreServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenreServiceInterface {
	mock := &MockGenreServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
