// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	models "myanimeapi/api/models"

	mock "github.com/stretchr/testify/mock"
)

// MockAnimeServiceInterface is an autogenerated mock type for the AnimeServiceInterface type
type MockAnimeServiceInterface struct {
	mock.Mock
}

type MockAnimeServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAnimeServiceInterface) EXPECT() *MockAnimeServiceInterface_Expecter {
	return &MockAnimeServiceInterface_Expecter{mock: &_m.Mock}
}

// AddGenresToAnime provides a mock function with given fields: ctx, animeID, genreIDs
func (_m *MockAnimeServiceInterface) AddGenresToAnime(ctx context.Context, animeID uint, genreIDs []uint) error {
	ret := _m.Called(ctx, animeID, genreIDs)

	if len(ret) == 0 {
		panic("no return value specified for AddGenresToAnime")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, []uint) error); ok {
		r0 = rf(ctx, animeID, genreIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAnimeServiceInterface_AddGenresToAnime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddGenresToAnime'
type MockAnimeServiceInterface_AddGenresToAnime_Call struct {
	*mock.Call
}

// AddGenresToAnime is a helper method to define mock.On call
//   - ctx context.Context
//   - animeID uint
//   - genreIDs []uint
func (_e *MockAnimeServiceInterface_Expecter) AddGenresToAnime(ctx interface{}, animeID interface{}, genreIDs interface{}) *MockAnimeServiceInterface_AddGenresToAnime_Call {
	return &MockAnimeServiceInterface_AddGenresToAnime_Call{Call: _e.mock.On("AddGenresToAnime", ctx, animeID, genreIDs)}
}

func (_c *MockAnimeServiceInterface_AddGenresToAnime_Call) Run(run func(ctx context.Context, animeID uint, genreIDs []uint)) *MockAnimeServiceInterface_AddGenresToAnime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].([]uint))
	})
	return _c
}

func (_c *MockAnimeServiceInterface_AddGenresToAnime_Call) Return(_a0 error) *MockAnimeServiceInterface_AddGenresToAnime_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAnimeServiceInterface_AddGenresToAnime_Call) RunAndReturn(run func(context.Context, uint, []uint) error) *MockAnimeServiceInterface_AddGenresToAnime_Call {
	_c.Call.Return(run)
	return _c
}

// AddTagsToAnime provides a mock function with given fields: ctx, animeID, tagIDs
func (_m *MockAnimeServiceInterface) AddTagsToAnime(ctx context.Context, animeID uint, tagIDs []uint) error {
	ret := _m.Called(ctx, animeID, tagIDs)

	if len(ret) == 0 {
		panic("no return value specified for AddTagsToAnime")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, []uint) error); ok {
		r0 = rf(ctx, animeID, tagIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAnimeServiceInterface_AddTagsToAnime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTagsToAnime'
type MockAnimeServiceInterface_AddTagsToAnime_Call struct {
	*mock.Call
}

// AddTagsToAnime is a helper method to define mock.On call
//   - ctx context.Context
//   - animeID uint
//   - tagIDs []uint
func (_e *MockAnimeServiceInterface_Expecter) AddTagsToAnime(ctx interface{}, animeID interface{}, tagIDs interface{}) *MockAnimeServiceInterface_AddTagsToAnime_Call {
	return &MockAnimeServiceInterface_AddTagsToAnime_Call{Call: _e.mock.On("AddTagsToAnime", ctx, animeID, tagIDs)}
}

func (_c *MockAnimeServiceInterface_AddTagsToAnime_Call) Run(run func(ctx context.Context, animeID uint, tagIDs []uint)) *MockAnimeServiceInterface_AddTagsToAnime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].([]uint))
	})
	return _c
}

func (_c *MockAnimeServiceInterface_AddTagsToAnime_Call) Return(_a0 error) *MockAnimeServiceInterface_AddTagsToAnime_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAnimeServiceInterface_AddTagsToAnime_Call) RunAndReturn(run func(context.Context, uint, []uint) error) *MockAnimeServiceInterface_AddTagsToAnime_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAnime provides a mock function with given fields: ctx, anime
func (_m *MockAnimeServiceInterface) CreateAnime(ctx context.Context, anime *models.Anime) error {
	ret := _m.Called(ctx, anime)

	if len(ret) == 0 {
		panic("no return value specified for CreateAnime")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Anime) error); ok {
		r0 = rf(ctx, anime)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAnimeServiceInterface_CreateAnime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAnime'
type MockAnimeServiceInterface_CreateAnime_Call struct {
	*mock.Call
}

// CreateAnime is a helper method to define mock.On call
//   - ctx context.Context
//   - anime *models.Anime
func (_e *MockAnimeServiceInterface_Expecter) CreateAnime(ctx interface{}, anime interface{}) *MockAnimeServiceInterface_CreateAnime_Call {
	return &MockAnimeServiceInterface_CreateAnime_Call{Call: _e.mock.On("CreateAnime", ctx, anime)}
}

func (_c *MockAnimeServiceInterface_CreateAnime_Call) Run(run func(ctx context.Context, anime *models.Anime)) *MockAnimeServiceInterface_CreateAnime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Anime))
	})
	return _c
}

func (_c *MockAnimeServiceInterface_CreateAnime_Call) Return(_a0 error) *MockAnimeServiceInterface_CreateAnime_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAnimeServiceInterface_CreateAnime_Call) RunAndReturn(run func(context.Context, *models.Anime) error) *MockAnimeServiceInterface_CreateAnime_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAnime provides a mock function with given fields: ctx, id
func (_m *MockAnimeServiceInterface) DeleteAnime(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAnime")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAnimeServiceInterface_DeleteAnime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAnime'
type MockAnimeServiceInterface_DeleteAnime_Call struct {
	*mock.Call
}

// DeleteAnime is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockAnimeServiceInterface_Expecter) DeleteAnime(ctx interface{}, id interface{}) *MockAnimeServiceInterface_DeleteAnime_Call {
	return &MockAnimeServiceInterface_DeleteAnime_Call{Call: _e.mock.On("DeleteAnime", ctx, id)}
}

func (_c *MockAnimeServiceInterface_DeleteAnime_Call) Run(run func(ctx context.Context, id uint)) *MockAnimeServiceInterface_DeleteAnime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockAnimeServiceInterface_DeleteAnime_Call) Return(_a0 error) *MockAnimeServiceInterface_DeleteAnime_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAnimeServiceInterface_DeleteAnime_Call) RunAndReturn(run func(context.Context, uint) error) *MockAnimeServiceInterface_DeleteAnime_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllAnimes provides a mock function with given fields: ctx, page, limit, filter
func (_m *MockAnimeServiceInterface) GetAllAnimes(ctx context.Context, page int, limit int, filter models.AnimeFilter) ([]*models.Anime, int64, error) {
	ret := _m.Called(ctx, page, limit, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAllAnimes")
	}

	var r0 []*models.Anime
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, models.AnimeFilter) ([]*models.Anime, int64, error)); ok {
		return rf(ctx, page, limit, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, models.AnimeFilter) []*models.Anime); ok {
		r0 = rf(ctx, page, limit, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Anime)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, models.AnimeFilter) int64); ok {
		r1 = rf(ctx, page, limit, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, models.AnimeFilter) error); ok {
		r2 = rf(ctx, page, limit, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAnimeServiceInterface_GetAllAnimes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllAnimes'
type MockAnimeServiceInterface_GetAllAnimes_Call struct {
	*mock.Call
}

// GetAllAnimes is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - limit int
//   - filter models.AnimeFilter
func (_e *MockAnimeServiceInterface_Expecter) GetAllAnimes(ctx interface{}, page interface{}, limit interface{}, filter interface{}) *MockAnimeServiceInterface_GetAllAnimes_Call {
	return &MockAnimeServiceInterface_GetAllAnimes_Call{Call: _e.mock.On("GetAllAnimes", ctx, page, limit, filter)}
}

func (_c *MockAnimeServiceInterface_GetAllAnimes_Call) Run(run func(ctx context.Context, page int, limit int, filter models.AnimeFilter)) *MockAnimeServiceInterface_GetAllAnimes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(models.AnimeFilter))
	})
	return _c
}

func (_c *MockAnimeServiceInterface_GetAllAnimes_Call) Return(_a0 []*models.Anime, _a1 int64, _a2 error) *MockAnimeServiceInterface_GetAllAnimes_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAnimeServiceInterface_GetAllAnimes_Call) RunAndReturn(run func(context.Context, int, int, models.AnimeFilter) ([]*models.Anime, int64, error)) *MockAnimeServiceInterface_GetAllAnimes_Call {
	_c.Call.Return(run)
	return _c
}

// GetAnimeByID provides a mock function with given fields: ctx, id
func (_m *MockAnimeServiceInterface) GetAnimeByID(ctx context.Context, id uint) (*models.Anime, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAnimeByID")
	}

	var r0 *models.Anime
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*models.Anime, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *models.Anime); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Anime)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAnimeServiceInterface_GetAnimeByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAnimeByID'
type MockAnimeServiceInterface_GetAnimeByID_Call struct {
	*mock.Call
}

// GetAnimeByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockAnimeServiceInterface_Expecter) GetAnimeByID(ctx interface{}, id interface{}) *MockAnimeServiceInterface_GetAnimeByID_Call {
	return &MockAnimeServiceInterface_GetAnimeByID_Call{Call: _e.mock.On("GetAnimeByID", ctx, id)}
}

func (_c *MockAnimeServiceInterface_GetAnimeByID_Call) Run(run func(ctx context.Context, id uint)) *MockAnimeServiceInterface_GetAnimeByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockAnimeServiceInterface_GetAnimeByID_Call) Return(_a0 *models.Anime, _a1 error) *MockAnimeServiceInterface_GetAnimeByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAnimeServiceInterface_GetAnimeByID_Call) RunAndReturn(run func(context.Context, uint) (*models.Anime, error)) *MockAnimeServiceInterface_GetAnimeByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAnimesByGenre provides a mock function with given fields: ctx, genre, page, limit
func (_m *MockAnimeServiceInterface) GetAnimesByGenre(ctx context.Context, genre string, page int, limit int) ([]*models.Anime, int64, error) {
	ret := _m.Called(ctx, genre, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetAnimesByGenre")
	}

	var r0 []*models.Anime
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*models.Anime, int64, error)); ok {
		return rf(ctx, genre, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []*models.Anime); ok {
		r0 = rf(ctx, genre, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Anime)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int64); ok {
		r1 = rf(ctx, genre, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, genre, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAnimeServiceInterface_GetAnimesByGenre_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAnimesByGenre'
type MockAnimeServiceInterface_GetAnimesByGenre_Call struct {
	*mock.Call
}

// GetAnimesByGenre is a helper method to define mock.On call
//   - ctx context.Context
//   - genre string
//   - page int
//   - limit int
func (_e *MockAnimeServiceInterface_Expecter) GetAnimesByGenre(ctx interface{}, genre interface{}, page interface{}, limit interface{}) *MockAnimeServiceInterface_GetAnimesByGenre_Call {
	return &MockAnimeServiceInterface_GetAnimesByGenre_Call{Call: _e.mock.On("GetAnimesByGenre", ctx, genre, page, limit)}
}

func (_c *MockAnimeServiceInterface_GetAnimesByGenre_Call) Run(run func(ctx context.Context, genre string, page int, limit int)) *MockAnimeServiceInterface_GetAnimesByGenre_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockAnimeServiceInterface_GetAnimesByGenre_Call) Return(_a0 []*models.Anime, _a1 int64, _a2 error) *MockAnimeServiceInterface_GetAnimesByGenre_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAnimeServiceInterface_GetAnimesByGenre_Call) RunAndReturn(run func(context.Context, string, int, int) ([]*models.Anime, int64, error)) *MockAnimeServiceInterface_GetAnimesByGenre_Call {
	_c.Call.Return(run)
	return _c
}

// GetAnimesByTitle provides a mock function with given fields: ctx, title, page, limit
func (_m *MockAnimeServiceInterface) GetAnimesByTitle(ctx context.Context, title string, page int, limit int) ([]*models.Anime, int64, error) {
	ret := _m.Called(ctx, title, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetAnimesByTitle")
	}

	var r0 []*models.Anime
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*models.Anime, int64, error)); ok {
		return rf(ctx, title, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []*models.Anime); ok {
		r0 = rf(ctx, title, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Anime)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int64); ok {
		r1 = rf(ctx, title, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, title, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAnimeServiceInterface_GetAnimesByTitle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAnimesByTitle'
type MockAnimeServiceInterface_GetAnimesByTitle_Call struct {
	*mock.Call
}

// GetAnimesByTitle is a helper method to define mock.On call
//   - ctx context.Context
//   - title string
//   - page int
//   - limit int
func (_e *MockAnimeServiceInterface_Expecter) GetAnimesByTitle(ctx interface{}, title interface{}, page interface{}, limit interface{}) *MockAnimeServiceInterface_GetAnimesByTitle_Call {
	return &MockAnimeServiceInterface_GetAnimesByTitle_Call{Call: _e.mock.On("GetAnimesByTitle", ctx, title, page, limit)}
}

func (_c *MockAnimeServiceInterface_GetAnimesByTitle_Call) Run(run func(ctx context.Context, title string, page int, limit int)) *MockAnimeServiceInterface_GetAnimesByTitle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockAnimeServiceInterface_GetAnimesByTitle_Call) Return(_a0 []*models.Anime, _a1 int64, _a2 error) *MockAnimeServiceInterface_GetAnimesByTitle_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAnimeServiceInterface_GetAnimesByTitle_Call) RunAndReturn(run func(context.Context, string, int, int) ([]*models.Anime, int64, error)) *MockAnimeServiceInterface_GetAnimesByTitle_Call {
	_c.Call.Return(run)
	return _c
}

// GetReviewsForAnime provides a mock function with given fields: ctx, animeID, page, limit
func (_m *MockAnimeServiceInterface) GetReviewsForAnime(ctx context.Context, animeID uint, page int, limit int) ([]*models.Review, int64, error) {
	ret := _m.Called(ctx, animeID, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetReviewsForAnime")
	}

	var r0 []*models.Review
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, int, int) ([]*models.Review, int64, error)); ok {
		return rf(ctx, animeID, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, int, int) []*models.Review); ok {
		r0 = rf(ctx, animeID, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Review)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, int, int) int64); ok {
		r1 = rf(ctx, animeID, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uint, int, int) error); ok {
		r2 = rf(ctx, animeID, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAnimeServiceInterface_GetReviewsForAnime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReviewsForAnime'
type MockAnimeServiceInterface_GetReviewsForAnime_Call struct {
	*mock.Call
}

// GetReviewsForAnime is a helper method to define mock.On call
//   - ctx context.Context
//   - animeID uint
//   - page int
//   - limit int
func (_e *MockAnimeServiceInterface_Expecter) GetReviewsForAnime(ctx interface{}, animeID interface{}, page interface{}, limit interface{}) *MockAnimeServiceInterface_GetReviewsForAnime_Call {
	return &MockAnimeServiceInterface_GetReviewsForAnime_Call{Call: _e.mock.On("GetReviewsForAnime", ctx, animeID, page, limit)}
}

func (_c *MockAnimeServiceInterface_GetReviewsForAnime_Call) Run(run func(ctx context.Context, animeID uint, page int, limit int)) *MockAnimeServiceInterface_GetReviewsForAnime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockAnimeServiceInterface_GetReviewsForAnime_Call) Return(_a0 []*models.Review, _a1 int64, _a2 error) *MockAnimeServiceInterface_GetReviewsForAnime_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAnimeServiceInterface_GetReviewsForAnime_Call) RunAndReturn(run func(context.Context, uint, int, int) ([]*models.Review, int64, error)) *MockAnimeServiceInterface_GetReviewsForAnime_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveGenresFromAnime provides a mock function with given fields: ctx, animeID, genreIDs
func (_m *MockAnimeServiceInterface) RemoveGenresFromAnime(ctx context.Context, animeID uint, genreIDs []uint) error {
	ret := _m.Called(ctx, animeID, genreIDs)

	if len(ret) == 0 {
		panic("no return value specified for RemoveGenresFromAnime")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, []uint) error); ok {
		r0 = rf(ctx, animeID, genreIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAnimeServiceInterface_RemoveGenresFromAnime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveGenresFromAnime'
type MockAnimeServiceInterface_RemoveGenresFromAnime_Call struct {
	*mock.Call
}

// RemoveGenresFromAnime is a helper method to define mock.On call
//   - ctx context.Context
//   - animeID uint
//   - genreIDs []uint
func (_e *MockAnimeServiceInterface_Expecter) RemoveGenresFromAnime(ctx interface{}, animeID interface{}, genreIDs interface{}) *MockAnimeServiceInterface_RemoveGenresFromAnime_Call {
	return &MockAnimeServiceInterface_RemoveGenresFromAnime_Call{Call: _e.mock.On("RemoveGenresFromAnime", ctx, animeID, genreIDs)}
}

func (_c *MockAnimeServiceInterface_RemoveGenresFromAnime_Call) Run(run func(ctx context.Context, animeID uint, genreIDs []uint)) *MockAnimeServiceInterface_RemoveGenresFromAnime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].([]uint))
	})
	return _c
}

func (_c *MockAnimeServiceInterface_RemoveGenresFromAnime_Call) Return(_a0 error) *MockAnimeServiceInterface_RemoveGenresFromAnime_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAnimeServiceInterface_RemoveGenresFromAnime_Call) RunAndReturn(run func(context.Context, uint, []uint) error) *MockAnimeServiceInterface_RemoveGenresFromAnime_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveTagsFromAnime provides a mock function with given fields: ctx, animeID, tagIDs
func (_m *MockAnimeServiceInterface) RemoveTagsFromAnime(ctx context.Context, animeID uint, tagIDs []uint) error {
	ret := _m.Called(ctx, animeID, tagIDs)

	if len(ret) == 0 {
		panic("no return value specified for RemoveTagsFromAnime")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, []uint) error); ok {
		r0 = rf(ctx, animeID, tagIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAnimeServiceInterface_RemoveTagsFromAnime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveTagsFromAnime'
type MockAnimeServiceInterface_RemoveTagsFromAnime_Call struct {
	*mock.Call
}

// RemoveTagsFromAnime is a helper method to define mock.On call
//   - ctx context.Context
//   - animeID uint
//   - tagIDs []uint
func (_e *MockAnimeServiceInterface_Expecter) RemoveTagsFromAnime(ctx interface{}, animeID interface{}, tagIDs interface{}) *MockAnimeServiceInterface_RemoveTagsFromAnime_Call {
	return &MockAnimeServiceInterface_RemoveTagsFromAnime_Call{Call: _e.mock.On("RemoveTagsFromAnime", ctx, animeID, tagIDs)}
}

func (_c *MockAnimeServiceInterface_RemoveTagsFromAnime_Call) Run(run func(ctx context.Context, animeID uint, tagIDs []uint)) *MockAnimeServiceInterface_RemoveTagsFromAnime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].([]uint))
	})
	return _c
}

func (_c *MockAnimeServiceInterface_RemoveTagsFromAnime_Call) Return(_a0 error) *MockAnimeServiceInterface_RemoveTagsFromAnime_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAnimeServiceInterface_RemoveTagsFromAnime_Call) RunAndReturn(run func(context.Context, uint, []uint) error) *MockAnimeServiceInterface_RemoveTagsFromAnime_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAnime provides a mock function with given fields: ctx, anime
func (_m *MockAnimeServiceInterface) UpdateAnime(ctx context.Context, anime *models.Anime) error {
	ret := _m.Called(ctx, anime)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAnime")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Anime) error); ok {
		r0 = rf(ctx, anime)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAnimeServiceInterface_UpdateAnime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAnime'
type MockAnimeServiceInterface_UpdateAnime_Call struct {
	*mock.Call
}

// UpdateAnime is a helper method to define mock.On call
//   - ctx context.Context
//   - anime *models.Anime
func (_e *MockAnimeServiceInterface_Expecter) UpdateAnime(ctx interface{}, anime interface{}) *MockAnimeServiceInterface_UpdateAnime_Call {
	return &MockAnimeServiceInterface_UpdateAnime_Call{Call: _e.mock.On("UpdateAnime", ctx, anime)}
}

func (_c *MockAnimeServiceInterface_UpdateAnime_Call) Run(run func(ctx context.Context, anime *models.Anime)) *MockAnimeServiceInterface_UpdateAnime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Anime))
	})
	return _c
}

func (_c *MockAnimeServiceInterface_UpdateAnime_Call) Return(_a0 error) *MockAnimeServiceInterface_UpdateAnime_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAnimeServiceInterface_UpdateAnime_Call) RunAndReturn(run func(context.Context, *models.Anime) error) *MockAnimeServiceInterface_UpdateAnime_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAnimeServiceInterface creates a new instance of MockAnimeServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAnimeServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAnimeServiceInterface {
	mock := &MockAnimeServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
