// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	models "myanimeapi/api/models"

	mock "github.com/stretchr/testify/mock"
)

// MockUserServiceInterface is an autogenerated mock type for the UserServiceInterface type
type MockUserServiceInterface struct {
	mock.Mock
}

type MockUserServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserServiceInterface) EXPECT() *MockUserServiceInterface_Expecter {
	return &MockUserServiceInterface_Expecter{mock: &_m.Mock}
}

// ChangePassword provides a mock function with given fields: ctx, userID, currentPassword, newPassword
func (_m *MockUserServiceInterface) ChangePassword(ctx context.Context, userID uint, currentPassword string, newPassword string) error {
	ret := _m.Called(ctx, userID, currentPassword, newPassword)

	if len(ret) == 0 {
		panic("no return value specified for ChangePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, string) error); ok {
		r0 = rf(ctx, userID, currentPassword, newPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserServiceInterface_ChangePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangePassword'
type MockUserServiceInterface_ChangePassword_Call struct {
	*mock.Call
}

// ChangePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - currentPassword string
//   - newPassword string
func (_e *MockUserServiceInterface_Expecter) ChangePassword(ctx interface{}, userID interface{}, currentPassword interface{}, newPassword interface{}) *MockUserServiceInterface_ChangePassword_Call {
	return &MockUserServiceInterface_ChangePassword_Call{Call: _e.mock.On("ChangePassword", ctx, userID, currentPassword, newPassword)}
}

func (_c *MockUserServiceInterface_ChangePassword_Call) Run(run func(ctx context.Context, userID uint, currentPassword string, newPassword string)) *MockUserServiceInterface_ChangePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockUserServiceInterface_ChangePassword_Call) Return(_a0 error) *MockUserServiceInterface_ChangePassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserServiceInterface_ChangePassword_Call) RunAndReturn(run func(context.Context, uint, string, string) error) *MockUserServiceInterface_ChangePassword_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: ctx, user
func (_m *MockUserServiceInterface) CreateUser(ctx context.Context, user *models.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserServiceInterface_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserServiceInterface_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *models.User
func (_e *MockUserServiceInterface_Expecter) CreateUser(ctx interface{}, user interface{}) *MockUserServiceInterface_CreateUser_Call {
	return &MockUserServiceInterface_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *MockUserServiceInterface_CreateUser_Call) Run(run func(ctx context.Context, user *models.User)) *MockUserServiceInterface_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.User))
	})
	return _c
}

func (_c *MockUserServiceInterface_CreateUser_Call) Return(_a0 error) *MockUserServiceInterface_CreateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserServiceInterface_CreateUser_Call) RunAndReturn(run func(context.Context, *models.User) error) *MockUserServiceInterface_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeactivateAccount provides a mock function with given fields: ctx, userID, password
func (_m *MockUserServiceInterface) DeactivateAccount(ctx context.Context, userID uint, password string) error {
	ret := _m.Called(ctx, userID, password)

	if len(ret) == 0 {
		panic("no return value specified for DeactivateAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string) error); ok {
		r0 = rf(ctx, userID, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserServiceInterface_DeactivateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeactivateAccount'
type MockUserServiceInterface_DeactivateAccount_Call struct {
	*mock.Call
}

// DeactivateAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - password string
func (_e *MockUserServiceInterface_Expecter) DeactivateAccount(ctx interface{}, userID interface{}, password interface{}) *MockUserServiceInterface_DeactivateAccount_Call {
	return &MockUserServiceInterface_DeactivateAccount_Call{Call: _e.mock.On("DeactivateAccount", ctx, userID, password)}
}

func (_c *MockUserServiceInterface_DeactivateAccount_Call) Run(run func(ctx context.Context, userID uint, password string)) *MockUserServiceInterface_DeactivateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(string))
	})
	return _c
}

func (_c *MockUserServiceInterface_DeactivateAccount_Call) Return(_a0 error) *MockUserServiceInterface_DeactivateAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserServiceInterface_DeactivateAccount_Call) RunAndReturn(run func(context.Context, uint, string) error) *MockUserServiceInterface_DeactivateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function with given fields: ctx, id
func (_m *MockUserServiceInterface) DeleteUser(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserServiceInterface_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockUserServiceInterface_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockUserServiceInterface_Expecter) DeleteUser(ctx interface{}, id interface{}) *MockUserServiceInterface_DeleteUser_Call {
	return &MockUserServiceInterface_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, id)}
}

func (_c *MockUserServiceInterface_DeleteUser_Call) Run(run func(ctx context.Context, id uint)) *MockUserServiceInterface_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockUserServiceInterface_DeleteUser_Call) Return(_a0 error) *MockUserServiceInterface_DeleteUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserServiceInterface_DeleteUser_Call) RunAndReturn(run func(context.Context, uint) error) *MockUserServiceInterface_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllUsers provides a mock function with given fields: ctx, page, limit
func (_m *MockUserServiceInterface) GetAllUsers(ctx context.Context, page int, limit int) ([]models.User, int64, error) {
	ret := _m.Called(ctx, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetAllUsers")
	}

	var r0 []models.User
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]models.User, int64, error)); ok {
		return rf(ctx, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []models.User); ok {
		r0 = rf(ctx, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int64); ok {
		r1 = rf(ctx, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockUserServiceInterface_GetAllUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllUsers'
type MockUserServiceInterface_GetAllUsers_Call struct {
	*mock.Call
}

// GetAllUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - limit int
func (_e *MockUserServiceInterface_Expecter) GetAllUsers(ctx interface{}, page interface{}, limit interface{}) *MockUserServiceInterface_GetAllUsers_Call {
	return &MockUserServiceInterface_GetAllUsers_Call{Call: _e.mock.On("GetAllUsers", ctx, page, limit)}
}

func (_c *MockUserServiceInterface_GetAllUsers_Call) Run(run func(ctx context.Context, page int, limit int)) *MockUserServiceInterface_GetAllUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockUserServiceInterface_GetAllUsers_Call) Return(_a0 []models.User, _a1 int64, _a2 error) *MockUserServiceInterface_GetAllUsers_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockUserServiceInterface_GetAllUsers_Call) RunAndReturn(run func(context.Context, int, int) ([]models.User, int64, error)) *MockUserServiceInterface_GetAllUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function with given fields: ctx, email
func (_m *MockUserServiceInterface) GetByEmail(ctx context.Context, email string) (*models.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserServiceInterface_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type MockUserServiceInterface_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserServiceInterface_Expecter) GetByEmail(ctx interface{}, email interface{}) *MockUserServiceInterface_GetByEmail_Call {
	return &MockUserServiceInterface_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *MockUserServiceInterface_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserServiceInterface_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserServiceInterface_GetByEmail_Call) Return(_a0 *models.User, _a1 error) *MockUserServiceInterface_GetByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserServiceInterface_GetByEmail_Call) RunAndReturn(run func(context.Context, string) (*models.User, error)) *MockUserServiceInterface_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockUserServiceInterface) GetByID(ctx context.Context, id uint) (*models.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*models.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *models.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserServiceInterface_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockUserServiceInterface_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockUserServiceInterface_Expecter) GetByID(ctx interface{}, id interface{}) *MockUserServiceInterface_GetByID_Call {
	return &MockUserServiceInterface_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockUserServiceInterface_GetByID_Call) Run(run func(ctx context.Context, id uint)) *MockUserServiceInterface_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockUserServiceInterface_GetByID_Call) Return(_a0 *models.User, _a1 error) *MockUserServiceInterface_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserServiceInterface_GetByID_Call) RunAndReturn(run func(context.Context, uint) (*models.User, error)) *MockUserServiceInterface_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUsername provides a mock function with given fields: ctx, username
func (_m *MockUserServiceInterface) GetByUsername(ctx context.Context, username string) (*models.User, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetByUsername")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = rf(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserServiceInterface_GetByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUsername'
type MockUserServiceInterface_GetByUsername_Call struct {
	*mock.Call
}

// GetByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockUserServiceInterface_Expecter) GetByUsername(ctx interface{}, username interface{}) *MockUserServiceInterface_GetByUsername_Call {
	return &MockUserServiceInterface_GetByUsername_Call{Call: _e.mock.On("GetByUsername", ctx, username)}
}

func (_c *MockUserServiceInterface_GetByUsername_Call) Run(run func(ctx context.Context, username string)) *MockUserServiceInterface_GetByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserServiceInterface_GetByUsername_Call) Return(_a0 *models.User, _a1 error) *MockUserServiceInterface_GetByUsername_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserServiceInterface_GetByUsername_Call) RunAndReturn(run func(context.Context, string) (*models.User, error)) *MockUserServiceInterface_GetByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function with given fields: ctx, user
func (_m *MockUserServiceInterface) UpdateUser(ctx context.Context, user *models.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserServiceInterface_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockUserServiceInterface_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *models.User
func (_e *MockUserServiceInterface_Expecter) UpdateUser(ctx interface{}, user interface{}) *MockUserServiceInterface_UpdateUser_Call {
	return &MockUserServiceInterface_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, user)}
}

func (_c *MockUserServiceInterface_UpdateUser_Call) Run(run func(ctx context.Context, user *models.User)) *MockUserServiceInterface_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.User))
	})
	return _c
}

func (_c *MockUserServiceInterface_UpdateUser_Call) Return(_a0 error) *MockUserServiceInterface_UpdateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserServiceInterface_UpdateUser_Call) RunAndReturn(run func(context.Context, *models.User) error) *MockUserServiceInterface_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateUser provides a mock function with given fields: ctx, username, password
func (_m *MockUserServiceInterface) ValidateUser(ctx context.Context, username string, password string) (*models.User, error) {
	ret := _m.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for ValidateUser")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.User, error)); ok {
		return rf(ctx, username, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.User); ok {
		r0 = rf(ctx, username, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserServiceInterface_ValidateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateUser'
type MockUserServiceInterface_ValidateUser_Call struct {
	*mock.Call
}

// ValidateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *MockUserServiceInterface_Expecter) ValidateUser(ctx interface{}, username interface{}, password interface{}) *MockUserServiceInterface_ValidateUser_Call {
	return &MockUserServiceInterface_ValidateUser_Call{Call: _e.mock.On("ValidateUser", ctx, username, password)}
}

func (_c *MockUserServiceInterface_ValidateUser_Call) Run(run func(ctx context.Context, username string, password string)) *MockUserServiceInterface_ValidateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserServiceInterface_ValidateUser_Call) Return(_a0 *models.User, _a1 error) *MockUserServiceInterface_ValidateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserServiceInterface_ValidateUser_Call) RunAndReturn(run func(context.Context, string, string) (*models.User, error)) *MockUserServiceInterface_ValidateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserServiceInterface creates a new instance of MockUserServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserServiceInterface {
	mock := &MockUserServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
