// api/routes/routes.go
// Package routes provides the routing for the application.
// It registers routes for different resources, such as anime, users, reviews, and authentication.
// It also serves Swagger documentation for API endpoints.
// The package uses the `gorilla/mux` package for routing and the `http-swagger` package to serve Swagger documentation.
package routes

import (
	"log"
	"myanimeapi/api/handlers"
	"myanimeapi/api/middleware"
	"net/http"

	_ "myanimeapi/cmd/docs"      // This is required to load the docs generated by Swaggo
	"myanimeapi/internal/errors" // Import the errors package

	"github.com/gorilla/mux"
	httpSwagger "github.com/swaggo/http-swagger"
)

// RegisterRoutes registers all routes for the application.
// It sets up routes for health checks, anime, users, reviews, and authentication.
// It also applies global middleware, such as logging, error handling and rate limiting.
//
// Parameters:
//   - router: A pointer to a `mux.Router` instance to register routes.
//   - swaggerURL: The URL path to the Swagger JSON file.
//   - animeHandler: A pointer to an `AnimeHandler` instance for anime-related routes.
//   - userHandler: A pointer to a `UserHandler` instance for user-related routes.
//   - reviewHandler: A pointer to a `ReviewHandler` instance for review-related routes.
//   - authHandler: A pointer to an `AuthHandler` instance for authentication-related routes.
//   - version: The current version of the API.
//
// Example usage:
//
//	router := mux.NewRouter()
//	RegisterRoutes(router, "/swagger/doc.json", animeHandler, userHandler, reviewHandler, authHandler, version)
//	http.ListenAndServe(":8080", router)
func RegisterRoutes(router *mux.Router, swaggerURL string, animeHandler *handlers.AnimeHandler, userHandler *handlers.UserHandler, reviewHandler *handlers.ReviewHandler, authHandler *handlers.AuthHandler, version string) {
	// Create a new rate limiter with a limit of 100 requests per minute
	rateLimiter := middleware.NewRateLimiter()

	// Apply rate limiting middleware
	router.Use(rateLimiter.RateLimitMiddleware)

	// Apply error handling middleware
	router.Use(middleware.ErrorHandlingMiddleware)

	// Apply global middleware
	router.Use(middleware.LoggingMiddleware)
	log.Println("Global middleware registered")

	// Create a versioned subrouter
	v1Router := router.PathPrefix("/v1").Subrouter()

	// Health check endpoint
	// @Summary Health check
	// @Description Check the health of the API and its dependencies
	// @Tags health
	// @Produce json
	// @Success 200 {string} string "OK"
	// @Failure 503 {string} string "Service Unavailable"
	// @Router /v1/health [get]
	v1Router.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {
		db := animeHandler.DB // Use the database instance from the animeHandler
		if db == nil {
			errors.WriteErrorResponse(w, http.StatusServiceUnavailable, errors.ErrServiceUnavailable, "Database instance not initialized", "The database instance is not initialized.")
			return
		}

		if db.IsHealthy() {
			w.WriteHeader(http.StatusOK)
			if _, err := w.Write([]byte("OK")); err != nil {
				errors.WriteErrorResponse(w, http.StatusInternalServerError, errors.ErrInternalServer, "Failed to write response", "An internal server error occurred while writing the response.")
				return
			}
		} else {
			errors.WriteErrorResponse(w, http.StatusServiceUnavailable, errors.ErrServiceUnavailable, "Database connection failed", "The database connection is not healthy.")
		}
	}).Methods("GET")
	log.Println("Health check endpoint registered")

	// Register version endpoint
	v1Router.HandleFunc("/version", VersionHandler(version)).Methods("GET")
	log.Println("Version endpoint registered")

	// Register anime routes
	animeHandler.RegisterAnimeRoutes(v1Router)
	log.Println("Anime routes registered")

	// Register user routes
	userHandler.RegisterUserRoutes(v1Router)
	log.Println("User routes registered")

	// Register review routes
	reviewHandler.RegisterReviewRoutes(v1Router)
	log.Println("Review routes registered")

	// Register auth routes
	authHandler.RegisterAuthRoutes(v1Router)
	log.Println("Auth routes registered")

	// Register Swagger documentation
	router.PathPrefix("/swagger/").Handler(httpSwagger.Handler(
		httpSwagger.URL(swaggerURL), // Path to swagger.json
		httpSwagger.UIConfig(map[string]string{
			"theme": "swagger-ui-dark.css", // Use the dark theme
			"title": "MyAnimeAPI Documentation",
			//			"customStyle": `
			//    	.topbar-wrapper img {
			//        	content: url('https://example.com/logo.png');
			//        	width: 100px;
			//        	height: auto;
			//    	}
			//	`,*/ // it will be generated later
			//"customFavicon": "https://example.com/favicon.ico", // Custom favicon(it will be generated later)
		}),
	))
	log.Println("Swagger documentation registered")
}

// VersionHandler returns a handler function for the /version endpoint.
// It responds with the current version of the API in JSON format.
//
// Parameters:
//   - version: The current version of the API (e.g., "1.0.0").
//
// Returns:
//   - http.HandlerFunc: A handler function for the /version endpoint.
func VersionHandler(version string) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		if _, err := w.Write([]byte(`{"version": "` + version + `"}`)); err != nil {
			log.Printf("Failed to write response: %v", err)
			errors.WriteErrorResponse(w, http.StatusInternalServerError, errors.ErrInternalServer, "Failed to write response", "An internal server error occurred while writing the response.")
			return
		}
	}
}
