// api/routes/routes.go
// Package routes provides the routing for the application.
// It registers routes for different resources, such as anime, users, reviews, and authentication.
// It also serves Swagger documentation for API endpoints.
// The package uses the `gorilla/mux` package for routing and the `http-swagger` package to serve Swagger documentation.
package routes

import (
	"context"
	"encoding/json"
	"net/http"
	"os"

	graphqladapter "myanimeapi/api/adapters/graphql"
	"myanimeapi/api/adapters/graphql/generated"
	httphandler "myanimeapi/api/adapters/http"
	"myanimeapi/api/adapters/cache"
	"myanimeapi/api/middleware"
	"myanimeapi/api/models"
	"myanimeapi/api/repositories"
	"myanimeapi/api/services"
	"myanimeapi/internal/db"
	"myanimeapi/internal/logger"

	_ "myanimeapi/cmd/docs"      // This is required to load the docs generated by Swaggo
	"myanimeapi/internal/errors" // Import the errors package

	gqlhandler "github.com/99designs/gqlgen/graphql/handler"
	"github.com/99designs/gqlgen/graphql/playground"
	"github.com/gorilla/mux"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

// RegisterRoutes registers all routes for the application.
// It sets up routes for health checks, anime, users, reviews, and authentication.
// It also applies global middleware, such as logging, error handling and rate limiting.
//
// Parameters:
//   - router: A pointer to a `mux.Router` instance to register routes.
//   - swaggerURL: The URL path to the Swagger JSON file.
//   - dbWrapper: A pointer to a `db.DBInterface` instance for database operations.
//   - storageSvc: A `services.StorageServiceInterface` instance for file storage operations.
//   - version: The current version of the API.
//
// Example usage:
//
//	router := mux.NewRouter()
//	RegisterRoutes(router, "/swagger/doc.json", dbWrapper, storageSvc, version)
//	http.ListenAndServe(":8080", router)
func RegisterRoutes(router *mux.Router, swaggerURL string, dbWrapper db.DBInterface, storageSvc services.StorageServiceInterface, version string) {
	log := logger.Get()

	// Create a new rate limiter with a limit of 100 requests per minute
	rateLimiter := middleware.NewRateLimiter()

	// Apply rate limiting middleware
	router.Use(rateLimiter.RateLimitMiddleware)

	// Apply error handling middleware
	router.Use(middleware.ErrorHandlingMiddleware)

	// Apply gzip compression middleware
	router.Use(middleware.GzipMiddleware)

	// Apply Prometheus metrics middleware
	router.Use(middleware.MetricsMiddleware)

	// Apply global middleware
	router.Use(middleware.LoggingMiddleware)
	log.Info("Global middleware registered")

	// Create a versioned subrouter
	v1Router := router.PathPrefix("/v1").Subrouter()

	// Health check endpoint
	// @Summary Health check
	// @Description Check the health of the API and its dependencies
	// @Tags health
	// @Produce json
	// @Success 200 {string} string "OK"
	// @Failure 503 {string} string "Service Unavailable"
	// @Router /v1/health [get]
	v1Router.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {
		logFields := map[string]interface{}{
			"method":     r.Method,
			"path":       r.URL.Path,
			"request_id": r.Context().Value(middleware.RequestIDContextKey),
		}

		if dbWrapper == nil {
			errors.WriteErrorResponse(w, http.StatusServiceUnavailable, errors.ErrServiceUnavailable, "Database instance not initialized", "The database instance is not initialized.", logFields)
			return
		}

		if dbWrapper.IsHealthy() {
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)
			response := models.Response{
				Status:  "success",
				Message: "Service is healthy",
				Data:    "OK",
			}
			if err := json.NewEncoder(w).Encode(response); err != nil {
				logFields["error"] = err.Error()
				errors.WriteErrorResponse(w, http.StatusInternalServerError, errors.ErrInternalServer, "Failed to encode response", "An internal server error occurred while encoding the response.", logFields)
				return
			}
		} else {
			errors.WriteErrorResponse(w, http.StatusServiceUnavailable, errors.ErrServiceUnavailable, "Database connection failed", "The database connection is not healthy.", logFields)
		}
	}).Methods("GET")
	log.Info("Health check endpoint registered")

	// Register version endpoint
	v1Router.HandleFunc("/version", VersionHandler(version, log)).Methods("GET")
	log.Info("Version endpoint registered")

	// Initialize repositories
	animeRepo := repositories.NewAnimeRepository(dbWrapper)
	userRepo := repositories.NewUserRepository(dbWrapper)
	reviewRepo := repositories.NewReviewRepository(dbWrapper)
	favoriteRepo := repositories.NewFavoriteRepository(dbWrapper)
	watchlistRepo := repositories.NewWatchlistRepository(dbWrapper)
	authRepo := repositories.NewAuthRepository(dbWrapper)
	genreRepo := repositories.NewGenreRepository(dbWrapper)
	tagRepo := repositories.NewTagRepository(dbWrapper)
	characterRepo := repositories.NewCharacterRepository(dbWrapper)
	log.Info("Repositories initialized")

	// Initialize cache output adapter.
	// When REDIS_URL is set, use Redis; otherwise fall back to a silent no-op so
	// the application works identically without Redis (graceful degradation).
	var cacheImpl cache.CacheInterface
	if redisURL := os.Getenv("REDIS_URL"); redisURL != "" {
		rc, err := cache.NewRedisCache(context.Background(), redisURL)
		if err != nil {
			log.WithField("error", err.Error()).Warning("Redis cache unavailable — falling back to no-op cache")
			cacheImpl = cache.NewNoopCache()
		} else {
			cacheImpl = rc
		}
	} else {
		log.Info("REDIS_URL not set — using no-op cache")
		cacheImpl = cache.NewNoopCache()
	}
	log.Info("Cache adapter initialized")

	// Initialize services
	animeService := services.NewAnimeService(animeRepo, genreRepo, tagRepo, reviewRepo, cacheImpl)
	userService := services.NewUserService(userRepo)
	reviewService := services.NewReviewService(reviewRepo, userRepo, animeRepo, storageSvc, cacheImpl)
	authService := services.NewAuthService(authRepo)
	favoriteService := services.NewFavoriteService(favoriteRepo, userRepo, animeRepo)
	watchlistService := services.NewWatchlistService(watchlistRepo)
	genreService := services.NewGenreService(genreRepo, cacheImpl)
	tagService := services.NewTagService(tagRepo, cacheImpl)
	characterService := services.NewCharacterService(characterRepo)
	emailService, err := services.NewEmailService()
	if err != nil {
		log.WithField("error", err.Error()).Warning("Email service not configured — password reset emails will be unavailable")
		emailService = nil
	}
	passwordResetService := services.NewPasswordResetService(userRepo, emailService, dbWrapper)
	log.Info("Services initialized")

	// Initialize handlers
	animeHandler := httphandler.NewAnimeHandler(animeService)
	userHandler := httphandler.NewUserHandler(userService, genreService, passwordResetService, dbWrapper)
	reviewHandler := httphandler.NewReviewHandler(reviewService, storageSvc)
	authHandler := httphandler.NewAuthHandler(authService, log)
	favoriteHandler := httphandler.NewFavoriteHandler(favoriteService)
	genreHandler := httphandler.NewGenreHandler(genreService)
	tagHandler := httphandler.NewTagHandler(tagService)
	log.Info("Handlers initialized")

	// Register anime routes
	animeHandler.RegisterAnimeRoutes(v1Router)
	log.Info("Anime routes registered")

	// Register user routes (rate limiter passed for forgot-password endpoint)
	userHandler.RegisterUserRoutes(v1Router, rateLimiter)
	log.Info("User routes registered")

	// Register review routes
	reviewHandler.RegisterReviewRoutes(v1Router)
	log.Info("Review routes registered")

	// Register auth routes
	authHandler.RegisterAuthRoutes(v1Router)
	log.Info("Auth routes registered")

	// Register favorite routes
	favoriteHandler.RegisterFavoriteRoutes(v1Router)
	log.Info("Favorite routes registered")

	// Register watchlist routes
	watchlistHandler := httphandler.NewWatchlistHandler(watchlistService)
	watchlistHandler.RegisterWatchlistRoutes(v1Router)
	log.Info("Watchlist routes registered")

	// Register genre routes
	genreHandler.RegisterGenreRoutes(v1Router)
	log.Info("Genre routes registered")

	// Register tag routes
	tagHandler.RegisterTagRoutes(v1Router)
	log.Info("Tag routes registered")

	// Register character routes
	characterHandler := httphandler.NewCharacterHandler(characterService)
	characterHandler.RegisterCharacterRoutes(v1Router)
	log.Info("Character routes registered")

	// Register ETL routes (admin-only data ingestion)
	etlHandler := httphandler.NewETLHandler(services.NewETLService(dbWrapper, cacheImpl))
	etlHandler.RegisterETLRoutes(v1Router)
	log.Info("ETL routes registered")

	// Register admin routes
	adminHandler := httphandler.NewAdminHandler(dbWrapper)
	adminHandler.RegisterAdminRoutes(v1Router)
	log.Info("Admin routes registered")

	// Register GraphQL adapter (second input port — same services, different protocol)
	gqlResolver := &graphqladapter.Resolver{
		AnimeService:     animeService,
		AuthService:      authService,
		GenreService:     genreService,
		UserService:      userService,
		CharacterService: characterService,
	}
	gqlSrv := gqlhandler.NewDefaultServer(generated.NewExecutableSchema(generated.Config{
		Resolvers: gqlResolver,
	}))
	v1Router.Handle("/graphql", gqlSrv)
	v1Router.Handle("/graphql/playground", playground.Handler("GraphQL Playground", "/v1/graphql"))
	log.Info("GraphQL endpoint registered at /v1/graphql")

	// Expose Prometheus metrics — intentionally on the root router (not v1) so it
	// is reachable without authentication and excluded from rate limiting.
	// @Summary Prometheus metrics
	// @Description Exposes runtime metrics in Prometheus text format (scrape endpoint).
	// @Tags monitoring
	// @Produce text/plain
	// @Success 200 {string} string "metrics"
	// @Router /metrics [get]
	router.Handle("/metrics", promhttp.Handler()).Methods("GET")
	log.Info("Prometheus /metrics endpoint registered")

	// Register Swagger documentation
	if swaggerURL != "" {
		router.PathPrefix("/swagger/").Handler(http.StripPrefix("/swagger/", http.FileServer(http.Dir(swaggerURL))))
	}
	log.Info("Swagger documentation registered")
}

// VersionHandler returns a handler function for the /version endpoint.
// It responds with the current version of the API in JSON format.
//
// Parameters:
//   - version: The current version of the API (e.g., "1.0.0").
//   - log: A pointer to a logger.Logger instance for structured logging.
//
// Returns:
//   - http.HandlerFunc: A handler function for the /version endpoint.
func VersionHandler(version string, log *logger.Logger) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		logFields := map[string]interface{}{
			"method":     r.Method,
			"path":       r.URL.Path,
			"request_id": r.Context().Value(middleware.RequestIDContextKey),
		}

		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		if _, err := w.Write([]byte(`{"version": "` + version + `"}`)); err != nil {
			logFields["error"] = err.Error()
			log.WithFields(logFields).Error("Failed to write response")
			errors.WriteErrorResponse(w, http.StatusInternalServerError, errors.ErrInternalServer, "Failed to write response", "An internal server error occurred while writing the response.", logFields)
			return
		}
	}
}
